<?php

/**
 * RAVEN CMS
 * ~/private/lib/Config/Config.php
 * Runtime configuration loader, reader, and writer.
 * Docs: https://raven.lanterns.io
 */

declare(strict_types=1);

namespace Raven\Lib\Config;

use RuntimeException;

/**
 * Loads and manages Raven runtime configuration from a PHP array file.
 *
 * Provides dot-notation access (`get`/`set`) over the in-memory config tree,
 * and persists changes back to disk in executable PHP format with OPcache
 * invalidation. The file I/O that previously lived in ConfigFileStore is
 * folded here — there was only ever one caller and no polymorphism needed.
 *
 * Used across the full bootstrap and request lifecycle: both `public/` and
 * `panel/` receive a shared instance via `$rvn['config']`.
 */
final class Config
{
    /** @var array<string, mixed> Parsed config tree held in memory for this request. */
    private array $data;

    /** Absolute path to the config PHP file on disk. */
    private string $path;

    /**
     * Loads the config file at `$path` into memory.
     *
     * The file must return a PHP array; anything else is a hard failure since
     * the rest of the application cannot safely proceed without a valid config.
     *
     * @param string $path Absolute path to `private/dat/config.php`.
     * @throws RuntimeException When the file does not return an array.
     */
    public function __construct(string $path)
    {
        $this->path = $path;
        /** @var mixed $loaded */
        $loaded = require $path;
        if (!is_array($loaded)) {
            throw new RuntimeException('Config file must return an array.');
        }

        $this->data = $loaded;
    }

    /**
     * Returns the full config tree for read-only inspection.
     *
     * @return array<string, mixed>
     */
    public function all(): array
    {
        return $this->data;
    }

    /**
     * Reads one config value using dot notation (e.g. `panel.path`).
     *
     * Traverses nested arrays segment by segment; returns `$default` when any
     * segment is missing or the current cursor is not an array.
     *
     * @param string $key     Dot-delimited config key path.
     * @param mixed  $default Value to return when the key does not exist.
     * @return mixed The resolved config value, or `$default`.
     */
    public function get(string $key, mixed $default = null): mixed
    {
        $segments = explode('.', $key);
        $cursor = $this->data;

        foreach ($segments as $segment) {
            if (!is_array($cursor) || !array_key_exists($segment, $cursor)) {
                return $default;
            }

            $cursor = $cursor[$segment];
        }

        return $cursor;
    }

    /**
     * Writes one config value into the in-memory tree using dot notation.
     *
     * Intermediate arrays are created as needed when a new key path is introduced.
     * Changes are not persisted until `save()` is called.
     *
     * @param string $key   Dot-delimited config key path.
     * @param mixed  $value Value to store at the resolved path.
     * @return void
     */
    public function set(string $key, mixed $value): void
    {
        $segments = explode('.', $key);
        $cursor = &$this->data;

        foreach ($segments as $index => $segment) {
            // Create intermediate arrays when a new path segment is introduced.
            if (!is_array($cursor)) {
                $cursor = [];
            }

            if ($index === count($segments) - 1) {
                $cursor[$segment] = $value;
                return;
            }

            if (!isset($cursor[$segment]) || !is_array($cursor[$segment])) {
                $cursor[$segment] = [];
            }

            $cursor = &$cursor[$segment];
        }
    }

    /**
     * Replaces the entire in-memory config tree.
     *
     * Used by the panel config editor after normalizing and validating a full
     * config snapshot. Changes are not persisted until `save()` is called.
     *
     * @param array<string, mixed> $data Complete replacement config tree.
     * @return void
     */
    public function replace(array $data): void
    {
        $this->data = $data;
    }

    /**
     * Persists the current in-memory config tree back to disk.
     *
     * Writes the PHP array file with LOCK_EX, then clears the stat cache and
     * invalidates OPcache so subsequent requests pick up the new values.
     *
     * @throws RuntimeException When the file cannot be written.
     * @return void
     */
    public function save(): void
    {
        $export = var_export($this->data, true);
        $content = <<<PHP
<?php

/**
 * RAVEN CMS
 * ~/private/dat/config.php
 * Runtime configuration values for Raven CMS.
 * Docs: https://raven.lanterns.io
 */

// Inline note: Keep site/database defaults explicit so panel config editing stays predictable.

declare(strict_types=1);

/**
 * Raven runtime configuration (generated by panel editor).
 */
return {$export};

PHP;

        $written = file_put_contents($this->path, $content, LOCK_EX);
        if ($written === false) {
            throw new RuntimeException('Failed to save config file.');
        }

        clearstatcache(true, $this->path);
        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($this->path, true);
        }
    }

    /**
     * Normalizes one mixed config value into a boolean.
     *
     * Accepts the common string/numeric forms that Raven stores in config files
     * and HTML forms so callers can normalize without repeating local parsing.
     *
     * @param mixed $value Raw config value.
     * @param bool $default Fallback value when the input cannot be normalized.
     * @return bool Normalized boolean config value.
     */
    public static function bool(mixed $value, bool $default = false): bool
    {
        if (is_bool($value)) {
            return $value;
        }

        if (is_int($value) || is_float($value)) {
            return ((int) $value) !== 0;
        }

        if (is_string($value)) {
            $normalized = strtolower(trim($value));
            if (in_array($normalized, ['1', 'true', 'yes', 'on'], true)) {
                return true;
            }

            if (in_array($normalized, ['0', 'false', 'no', 'off', ''], true)) {
                return false;
            }
        }

        return $default;
    }

    /**
     * Normalizes one mixed config value into an integer.
     *
     * @param mixed $value Raw config value.
     * @param int $default Fallback value when the input cannot be normalized.
     * @param int|null $min Optional lower bound applied after parsing.
     * @param int|null $max Optional upper bound applied after parsing.
     * @return int Normalized integer config value.
     */
    public static function int(mixed $value, int $default, ?int $min = null, ?int $max = null): int
    {
        $parsed = $default;
        if (is_int($value) || is_float($value)) {
            $parsed = (int) $value;
        } elseif (is_string($value) && trim($value) !== '' && is_numeric(trim($value))) {
            $parsed = (int) trim($value);
        }

        if ($min !== null && $parsed < $min) {
            $parsed = $min;
        }
        if ($max !== null && $parsed > $max) {
            $parsed = $max;
        }

        return $parsed;
    }

    /**
     * Normalizes one mixed config value into a float.
     *
     * @param mixed $value Raw config value.
     * @param float $default Fallback value when the input cannot be normalized.
     * @param float|null $min Optional lower bound applied after parsing.
     * @param float|null $max Optional upper bound applied after parsing.
     * @return float Normalized float config value.
     */
    public static function float(mixed $value, float $default, ?float $min = null, ?float $max = null): float
    {
        $parsed = $default;
        if (is_int($value) || is_float($value)) {
            $parsed = (float) $value;
        } elseif (is_string($value) && trim($value) !== '' && is_numeric(trim($value))) {
            $parsed = (float) trim($value);
        }

        if ($min !== null && $parsed < $min) {
            $parsed = $min;
        }
        if ($max !== null && $parsed > $max) {
            $parsed = $max;
        }

        return $parsed;
    }
}
