<?php

/**
 * RAVEN CMS
 * ~/private/lib/Config/ConfigWriter.php
 * Handles the on-disk persistence format for Raven runtime config files.
 * Docs: https://raven.lanterns.io
 */

declare(strict_types=1);

namespace Raven\Lib\Config;

use RuntimeException;

/**
 * Writes a PHP config array to disk in the canonical Raven config-file format.
 *
 * Encapsulates the var_export serialization, file header generation, atomic
 * write, stat-cache invalidation, and OPcache eviction so that the runtime
 * Config class in sys/ stays focused on in-memory read/write operations and
 * never needs to own the on-disk format details.
 */
final class ConfigWriter
{
    /**
     * Persists a config array to a PHP file at the given path.
     *
     * Writes the canonical Raven config file format (PHP array return file)
     * with LOCK_EX, then clears the stat cache and invalidates OPcache so
     * subsequent requests pick up the new values immediately.
     *
     * @param string $path Absolute path to the config file on disk.
     * @param array<string, mixed> $data Config tree to persist.
     * @throws RuntimeException When the file cannot be written.
     * @return void
     */
    public static function persist(string $path, array $data): void
    {
        $export = var_export($data, true);
        $content = <<<PHP
<?php

/**
 * RAVEN CMS
 * ~/private/dat/config.php
 * Runtime configuration values for Raven CMS.
 * Docs: https://raven.lanterns.io
 */

// Inline note: Keep site/database defaults explicit so panel config editing stays predictable.

declare(strict_types=1);

/**
 * Raven runtime configuration (generated by panel editor).
 */
return {$export};

PHP;

        $written = file_put_contents($path, $content, LOCK_EX);
        if ($written === false) {
            throw new RuntimeException('Failed to save config file.');
        }

        clearstatcache(true, $path);
        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($path, true);
        }
    }
}
