<?php

declare(strict_types=1);

namespace Raven\Lib\Config;

use RuntimeException;

/**
 * Shared filesystem backend for loading/saving Raven config PHP array files.
 */
final class ConfigFileStore
{
    /**
     * @return array<string, mixed>
     */
    public function load(string $path): array
    {
        /** @var mixed $loaded */
        $loaded = require $path;
        if (!is_array($loaded)) {
            throw new RuntimeException('Config file must return an array.');
        }

        return $loaded;
    }

    /**
     * @param array<string, mixed> $data
     */
    public function save(string $path, array $data): void
    {
        $export = var_export($data, true);
        $content = <<<PHP
<?php

/**
 * RAVEN CMS
 * ~/private/config.php
 * Runtime configuration values for Raven CMS.
 * Docs: https://raven.lanterns.io
 */

// Inline note: Keep site/database defaults explicit so panel config editing stays predictable.

declare(strict_types=1);

/**
 * Raven runtime configuration (generated by panel editor).
 */
return {$export};

PHP;

        $written = file_put_contents($path, $content, LOCK_EX);
        if ($written === false) {
            throw new RuntimeException('Failed to save config file.');
        }

        clearstatcache(true, $path);
        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($path, true);
        }
    }
}
