<?php

/**
 * RAVEN CMS
 * ~/public/install.php
 * One-time installer for initial Raven CMS setup.
 * Docs: https://raven.lanterns.io
 */

// Inline note: This script is intentionally standalone so first-run setup works before full app bootstrap.

declare(strict_types=1);

use Raven\Core\Database\ConnectionFactory;
use Raven\Core\Database\SchemaManager;
use Raven\Repository\GroupRepository;
use Raven\Repository\UserRepository;

/**
 * Escapes text for HTML output.
 */
function installer_e(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
}

/**
 * Returns true when a path is absolute on Unix or Windows.
 */
function installer_is_absolute_path(string $path): bool
{
    if ($path === '') {
        return false;
    }

    return str_starts_with($path, '/')
        || preg_match('/^[A-Za-z]:[\\\\\\/]/', $path) === 1;
}

/**
 * Normalizes a configured path and resolves relative paths under project root.
 */
function installer_normalize_path(string $path, string $root): string
{
    $path = trim(str_replace('\\', '/', $path));
    if ($path === '') {
        return '';
    }

    if (installer_is_absolute_path($path)) {
        return rtrim($path, '/');
    }

    return rtrim($root, '/') . '/' . ltrim($path, '/');
}

/**
 * Persists runtime config to private/config.php with the standard header block.
 *
 * @param array<string, mixed> $config
 */
function installer_write_config(string $path, array $config): void
{
    $export = var_export($config, true);

    $content = "<?php\n\n";
    $content .= "/**\n";
    $content .= " * RAVEN CMS\n";
    $content .= " * ~/private/config.php\n";
    $content .= " * Runtime configuration values for Raven CMS.\n";
    $content .= " * Docs: https://raven.lanterns.io\n";
    $content .= " */\n\n";
    $content .= "// Inline note: Keep site/database defaults explicit so panel config editing stays predictable.\n\n";
    $content .= "declare(strict_types=1);\n\n";
    $content .= "/**\n";
    $content .= " * Raven runtime configuration (generated by installer).\n";
    $content .= " */\n";
    $content .= "return " . $export . ";\n";

    $written = file_put_contents($path, $content, LOCK_EX);
    if ($written === false) {
        throw new RuntimeException('Failed to write private/config.php');
    }
}

$root = dirname(__DIR__);
$configPath = $root . '/private/config.php';
$configTemplatePath = $root . '/private/config.php.dist';
$extensionStatePath = $root . '/private/ext/.state.php';
$extensionStateTemplatePath = $root . '/private/ext/.state.php.dist';
$lockPath = $root . '/private/tmp/install.lock';

// Installer lock is checked first to keep re-entry behavior deterministic.
if (is_file($lockPath)) {
    header('Location: /', true, 302);
    exit;
}

// Bring in Composer dependencies first; fallback autoloader keeps local classes available pre-install.
$composerAutoload = $root . '/composer/autoload.php';
if (is_file($composerAutoload)) {
    require_once $composerAutoload;
}

spl_autoload_register(static function (string $class) use ($root): void {
    $prefix = 'Raven\\';
    if (!str_starts_with($class, $prefix)) {
        return;
    }

    $relative = str_replace('\\', '/', substr($class, strlen($prefix)));
    $path = $root . '/private/src/' . $relative . '.php';
    if (is_file($path)) {
        require_once $path;
    }
});

// Session-backed CSRF token protects this high-impact setup endpoint.
if (session_status() !== PHP_SESSION_ACTIVE) {
    session_name('raven_install');
    session_set_cookie_params([
        'lifetime' => 0,
        'path' => '/',
        'domain' => '',
        'secure' => (!empty($_SERVER['HTTPS']) && strtolower((string) $_SERVER['HTTPS']) !== 'off'),
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    session_start();
}

if (!isset($_SESSION['_raven_install_csrf']) || !is_string($_SESSION['_raven_install_csrf'])) {
    $_SESSION['_raven_install_csrf'] = bin2hex(random_bytes(32));
}
$csrfToken = (string) $_SESSION['_raven_install_csrf'];

/** @var mixed $rawTemplate */
$rawTemplate = is_file($configTemplatePath) ? require $configTemplatePath : [];
$template = is_array($rawTemplate) ? $rawTemplate : [];

/** @var mixed $rawExisting */
$rawExisting = is_file($configPath) ? require $configPath : [];
$existing = is_array($rawExisting) ? $rawExisting : [];

$defaultConfig = $existing !== [] ? $existing : $template;

// Baseline defaults keep first render usable even when template file is missing.
$form = [
    'site_domain' => trim((string) ($defaultConfig['site']['domain'] ?? '')),
    'site_name' => trim((string) ($defaultConfig['site']['name'] ?? 'Raven CMS')),
    'panel_path' => trim((string) ($defaultConfig['panel']['path'] ?? 'panel')),
    'db_driver' => strtolower(trim((string) ($defaultConfig['database']['driver'] ?? 'sqlite'))),
    'db_table_prefix' => trim((string) ($defaultConfig['database']['table_prefix'] ?? 'raven_')),
    'sqlite_base_path' => trim((string) ($defaultConfig['database']['sqlite']['base_path'] ?? ($root . '/private/db'))),
    'mysql_host' => trim((string) ($defaultConfig['database']['mysql']['host'] ?? '127.0.0.1')),
    'mysql_port' => trim((string) ($defaultConfig['database']['mysql']['port'] ?? '3306')),
    'mysql_dbname' => trim((string) ($defaultConfig['database']['mysql']['dbname'] ?? 'raven')),
    'mysql_user' => trim((string) ($defaultConfig['database']['mysql']['user'] ?? 'raven')),
    'mysql_password' => '',
    'mysql_charset' => trim((string) ($defaultConfig['database']['mysql']['charset'] ?? 'utf8mb4')),
    'pgsql_host' => trim((string) ($defaultConfig['database']['pgsql']['host'] ?? '127.0.0.1')),
    'pgsql_port' => trim((string) ($defaultConfig['database']['pgsql']['port'] ?? '5432')),
    'pgsql_dbname' => trim((string) ($defaultConfig['database']['pgsql']['dbname'] ?? 'raven')),
    'pgsql_user' => trim((string) ($defaultConfig['database']['pgsql']['user'] ?? 'raven')),
    'pgsql_password' => '',
    'admin_username' => 'superadmin',
    'admin_display_name' => 'Super Admin',
    'admin_email' => 'admin@example.com',
    'admin_password' => '',
    'admin_password_confirm' => '',
];

$errors = [];

if (strtoupper((string) ($_SERVER['REQUEST_METHOD'] ?? 'GET')) === 'POST') {
    foreach ($form as $key => $_) {
        $form[$key] = trim((string) ($_POST[$key] ?? ''));
    }

    if (!hash_equals($csrfToken, (string) ($_POST['_csrf'] ?? ''))) {
        $errors[] = 'Invalid form token. Reload the page and try again.';
    }

    $driver = strtolower($form['db_driver']);
    if (!in_array($driver, ['sqlite', 'mysql', 'pgsql'], true)) {
        $errors[] = 'Database driver must be sqlite, mysql, or pgsql.';
    }

    $siteDomain = $form['site_domain'];
    $siteName = $form['site_name'];
    $panelPath = strtolower($form['panel_path']);

    if ($siteDomain === '') {
        $errors[] = 'Site domain is required.';
    }
    if ($siteName === '') {
        $errors[] = 'Site name is required.';
    }
    if ($panelPath === '' || preg_match('/^[a-z0-9][a-z0-9_-]*$/', $panelPath) !== 1) {
        $errors[] = 'Panel path must contain only lowercase letters, numbers, underscores, or dashes.';
    }

    $tablePrefix = preg_replace('/[^a-zA-Z0-9_]/', '', $form['db_table_prefix']) ?? '';
    if ($driver === 'sqlite') {
        $sqliteBasePath = installer_normalize_path($form['sqlite_base_path'], $root);
        if ($sqliteBasePath === '') {
            $errors[] = 'SQLite base path is required.';
        }
    } else {
        $sqliteBasePath = trim((string) ($template['database']['sqlite']['base_path'] ?? ($root . '/private/db')));
    }

    $mysqlPort = (int) $form['mysql_port'];
    if ($driver === 'mysql') {
        if ($form['mysql_host'] === '' || $form['mysql_dbname'] === '' || $form['mysql_user'] === '') {
            $errors[] = 'MySQL host, database, and user are required.';
        }
        if ($mysqlPort < 1 || $mysqlPort > 65535) {
            $errors[] = 'MySQL port must be between 1 and 65535.';
        }
        if ($form['mysql_charset'] === '') {
            $errors[] = 'MySQL charset is required.';
        }
    }

    $pgsqlPort = (int) $form['pgsql_port'];
    if ($driver === 'pgsql') {
        if ($form['pgsql_host'] === '' || $form['pgsql_dbname'] === '' || $form['pgsql_user'] === '') {
            $errors[] = 'PostgreSQL host, database, and user are required.';
        }
        if ($pgsqlPort < 1 || $pgsqlPort > 65535) {
            $errors[] = 'PostgreSQL port must be between 1 and 65535.';
        }
    }

    $adminUsername = $form['admin_username'];
    $adminDisplayName = $form['admin_display_name'] !== '' ? $form['admin_display_name'] : $adminUsername;
    $adminEmail = $form['admin_email'];
    $adminPassword = $form['admin_password'];
    $adminPasswordConfirm = $form['admin_password_confirm'];

    if ($adminUsername === '' || preg_match('/^[a-zA-Z0-9_.-]{3,100}$/', $adminUsername) !== 1) {
        $errors[] = 'Admin username must be 3-100 characters using letters, numbers, dot, underscore, or dash.';
    }
    if ($adminEmail === '' || filter_var($adminEmail, FILTER_VALIDATE_EMAIL) === false) {
        $errors[] = 'A valid admin email is required.';
    }
    if (strlen($adminPassword) < 8) {
        $errors[] = 'Admin password must be at least 8 characters.';
    }
    if (!hash_equals($adminPassword, $adminPasswordConfirm)) {
        $errors[] = 'Admin password confirmation does not match.';
    }

    if ($errors === []) {
        $nextConfig = is_array($template) && $template !== [] ? $template : [];

        // Keep installer output aligned with panel config editor expectations.
        $nextConfig['site'] = [
            'domain' => $siteDomain,
            'name' => $siteName,
            'enabled' => 'public',
            'default_theme' => trim((string) ($nextConfig['site']['default_theme'] ?? 'raven')) !== ''
                ? trim((string) ($nextConfig['site']['default_theme'] ?? 'raven'))
                : 'raven',
        ];

        $nextConfig['panel'] = is_array($nextConfig['panel'] ?? null) ? $nextConfig['panel'] : [];
        $nextConfig['panel']['path'] = $panelPath;
        if (!array_key_exists('default_theme', $nextConfig['panel'])) {
            $nextConfig['panel']['default_theme'] = 'light';
        }
        if (!array_key_exists('brand_name', $nextConfig['panel'])) {
            $nextConfig['panel']['brand_name'] = $siteName;
        }
        if (!array_key_exists('brand_logo', $nextConfig['panel'])) {
            $nextConfig['panel']['brand_logo'] = '';
        }
        unset($nextConfig['public']);

        $nextConfig['database'] = [
            'driver' => $driver,
            'sqlite' => [
                'base_path' => $sqliteBasePath,
            ],
            'mysql' => [
                'host' => $form['mysql_host'],
                'port' => $mysqlPort > 0 ? $mysqlPort : 3306,
                'dbname' => $form['mysql_dbname'],
                'user' => $form['mysql_user'],
                'password' => $form['mysql_password'],
                'charset' => $form['mysql_charset'] !== '' ? $form['mysql_charset'] : 'utf8mb4',
            ],
            'pgsql' => [
                'host' => $form['pgsql_host'],
                'port' => $pgsqlPort > 0 ? $pgsqlPort : 5432,
                'dbname' => $form['pgsql_dbname'],
                'user' => $form['pgsql_user'],
                'password' => $form['pgsql_password'],
            ],
            'table_prefix' => $tablePrefix,
        ];

        // Installer replaces bootstrap seeding; remove any legacy key entirely.
        unset($nextConfig['bootstrap_admin']);

        try {
            // Create SQLite storage directory only when SQLite is selected during install.
            if ($driver === 'sqlite') {
                if (!is_dir($sqliteBasePath) && !mkdir($sqliteBasePath, 0775, true) && !is_dir($sqliteBasePath)) {
                    throw new RuntimeException('Failed to create SQLite base path directory.');
                }
            }

            $connectionFactory = new ConnectionFactory((array) ($nextConfig['database'] ?? []));
            $driverName = $connectionFactory->getDriver();
            $prefix = $connectionFactory->getPrefix();

            $appDb = $connectionFactory->createAppConnection();
            $authDb = $connectionFactory->createAuthConnection();

            $schema = new SchemaManager();
            $schema->ensure($appDb, $authDb, $driverName, $prefix);

            $users = new UserRepository($authDb, $appDb, $driverName, $prefix);
            if ($users->listAll() !== []) {
                throw new RuntimeException('Installer can only create the initial admin on an empty user database.');
            }

            $groups = new GroupRepository($appDb, $driverName, $prefix);
            $superAdminGroupId = $groups->idBySlug('super');
            $userGroupId = $groups->idBySlug('user');

            if ($superAdminGroupId === null || $userGroupId === null) {
                throw new RuntimeException('Stock groups were not created correctly.');
            }

            $users->save([
                'id' => null,
                'username' => $adminUsername,
                'display_name' => $adminDisplayName,
                'email' => $adminEmail,
                'theme' => 'default',
                'password' => $adminPassword,
                'group_ids' => [$superAdminGroupId, $userGroupId],
            ]);

            installer_write_config($configPath, $nextConfig);

            // Seed runtime extension state from committed defaults template.
            if (!is_file($extensionStateTemplatePath)) {
                throw new RuntimeException('Missing extension state template private/ext/.state.php.dist.');
            }

            $stateTemplateContent = file_get_contents($extensionStateTemplatePath);
            if ($stateTemplateContent === false || trim($stateTemplateContent) === '') {
                throw new RuntimeException('Extension state template is unreadable or empty.');
            }

            $stateDirectory = dirname($extensionStatePath);
            if (!is_dir($stateDirectory) && !mkdir($stateDirectory, 0775, true) && !is_dir($stateDirectory)) {
                throw new RuntimeException('Failed to create extension state directory.');
            }

            if (file_put_contents($extensionStatePath, $stateTemplateContent, LOCK_EX) === false) {
                throw new RuntimeException('Failed to write private/ext/.state.php.');
            }

            $lockDirectory = dirname($lockPath);
            if (!is_dir($lockDirectory) && !mkdir($lockDirectory, 0775, true) && !is_dir($lockDirectory)) {
                throw new RuntimeException('Failed to create installer lock directory.');
            }

            $lockContent = "Raven CMS installer lock\nInstalled at (UTC): " . gmdate('c') . "\n";
            if (file_put_contents($lockPath, $lockContent, LOCK_EX) === false) {
                throw new RuntimeException('Failed to write installer lock file.');
            }

            header('Location: /', true, 302);
            exit;
        } catch (\Throwable $exception) {
            $errors[] = 'Installation failed: ' . $exception->getMessage();
        }
    }
}
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Raven CMS Installer</title>
    <style>
        body { font-family: sans-serif; background: #f4f6f8; color: #1a1f24; margin: 0; }
        .wrap { max-width: 920px; margin: 2rem auto; padding: 0 1rem 2rem; }
        .card { background: #fff; border: 1px solid #d7dde5; border-radius: 8px; padding: 1.25rem; margin-bottom: 1rem; }
        h1, h2 { margin: 0 0 0.8rem; }
        h1 { font-size: 1.45rem; }
        h2 { font-size: 1.05rem; border-bottom: 1px solid #edf1f5; padding-bottom: 0.45rem; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0.85rem 1rem; }
        .field { display: flex; flex-direction: column; gap: 0.3rem; }
        .field.full { grid-column: 1 / -1; }
        label { font-size: 0.9rem; font-weight: 600; }
        input, select { border: 1px solid #b8c3d1; border-radius: 6px; padding: 0.5rem 0.55rem; font-size: 0.95rem; }
        .note { font-size: 0.86rem; color: #4d5b6b; margin-top: 0.25rem; }
        .alert { border-radius: 6px; padding: 0.8rem 0.9rem; margin-bottom: 1rem; }
        .alert.error { background: #fcebec; border: 1px solid #f3b4b8; color: #7a1f26; }
        .actions { display: flex; justify-content: flex-end; margin-top: 1rem; }
        button { background: #154f95; color: #fff; border: 0; border-radius: 6px; padding: 0.62rem 1rem; font-size: 0.95rem; cursor: pointer; }
        button:hover { background: #123f77; }
        [data-driver-section] { display: none; }
        @media (max-width: 800px) { .grid { grid-template-columns: 1fr; } }
    </style>
</head>
<body>
<div class="wrap">
    <div class="card">
        <h1>Raven CMS Installer</h1>
        <p class="note">
            This installer writes <code>private/config.php</code>, initializes database schema, creates the first Super Admin account,
            seeds <code>private/ext/.state.php</code> from <code>private/ext/.state.php.dist</code>,
            and then writes a lock file at <code>private/tmp/install.lock</code>.
            Delete <code>public/install.php</code> after setup.
        </p>
    </div>

    <?php if ($errors !== []): ?>
        <div class="alert error">
            <strong>Install could not complete.</strong>
            <ul>
                <?php foreach ($errors as $error): ?>
                    <li><?= installer_e($error) ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <form method="post" action="/install.php" novalidate>
        <input type="hidden" name="_csrf" value="<?= installer_e($csrfToken) ?>">

        <div class="card">
            <h2>Site</h2>
            <div class="grid">
                <div class="field">
                    <label for="site_domain">Domain</label>
                    <input id="site_domain" name="site_domain" value="<?= installer_e($form['site_domain']) ?>" required>
                    <div class="note">Example: <code>example.com</code></div>
                </div>
                <div class="field">
                    <label for="site_name">Site Name</label>
                    <input id="site_name" name="site_name" value="<?= installer_e($form['site_name']) ?>" required>
                </div>
                <div class="field">
                    <label for="panel_path">Panel Path</label>
                    <input id="panel_path" name="panel_path" value="<?= installer_e($form['panel_path']) ?>" required>
                    <div class="note">Example: <code>panel</code> for <code>/panel</code></div>
                </div>
            </div>
        </div>

        <div class="card">
            <h2>Database</h2>
            <div class="grid">
                <div class="field">
                    <label for="db_driver">Driver</label>
                    <select id="db_driver" name="db_driver" required>
                        <option value="sqlite"<?= $form['db_driver'] === 'sqlite' ? ' selected' : '' ?>>SQLite</option>
                        <option value="mysql"<?= $form['db_driver'] === 'mysql' ? ' selected' : '' ?>>MySQL / MariaDB</option>
                        <option value="pgsql"<?= $form['db_driver'] === 'pgsql' ? ' selected' : '' ?>>PostgreSQL</option>
                    </select>
                </div>
                <div class="field">
                    <label for="db_table_prefix">Table Prefix (MySQL/PostgreSQL)</label>
                    <input id="db_table_prefix" name="db_table_prefix" value="<?= installer_e($form['db_table_prefix']) ?>">
                </div>
            </div>

            <div class="grid" data-driver-section="sqlite">
                <div class="field full">
                    <label for="sqlite_base_path">SQLite Base Path</label>
                    <input id="sqlite_base_path" name="sqlite_base_path" value="<?= installer_e($form['sqlite_base_path']) ?>">
                    <div class="note">SQLite database filenames are managed automatically by Raven for consistency.</div>
                </div>
            </div>

            <div class="grid" data-driver-section="mysql">
                <div class="field"><label for="mysql_host">MySQL Host</label><input id="mysql_host" name="mysql_host" value="<?= installer_e($form['mysql_host']) ?>"></div>
                <div class="field"><label for="mysql_port">MySQL Port</label><input id="mysql_port" name="mysql_port" value="<?= installer_e($form['mysql_port']) ?>"></div>
                <div class="field"><label for="mysql_dbname">MySQL Database</label><input id="mysql_dbname" name="mysql_dbname" value="<?= installer_e($form['mysql_dbname']) ?>"></div>
                <div class="field"><label for="mysql_user">MySQL User</label><input id="mysql_user" name="mysql_user" value="<?= installer_e($form['mysql_user']) ?>"></div>
                <div class="field"><label for="mysql_password">MySQL Password</label><input id="mysql_password" name="mysql_password" type="password" value="<?= installer_e($form['mysql_password']) ?>"></div>
                <div class="field"><label for="mysql_charset">MySQL Charset</label><input id="mysql_charset" name="mysql_charset" value="<?= installer_e($form['mysql_charset']) ?>"></div>
            </div>

            <div class="grid" data-driver-section="pgsql">
                <div class="field"><label for="pgsql_host">PostgreSQL Host</label><input id="pgsql_host" name="pgsql_host" value="<?= installer_e($form['pgsql_host']) ?>"></div>
                <div class="field"><label for="pgsql_port">PostgreSQL Port</label><input id="pgsql_port" name="pgsql_port" value="<?= installer_e($form['pgsql_port']) ?>"></div>
                <div class="field"><label for="pgsql_dbname">PostgreSQL Database</label><input id="pgsql_dbname" name="pgsql_dbname" value="<?= installer_e($form['pgsql_dbname']) ?>"></div>
                <div class="field"><label for="pgsql_user">PostgreSQL User</label><input id="pgsql_user" name="pgsql_user" value="<?= installer_e($form['pgsql_user']) ?>"></div>
                <div class="field"><label for="pgsql_password">PostgreSQL Password</label><input id="pgsql_password" name="pgsql_password" type="password" value="<?= installer_e($form['pgsql_password']) ?>"></div>
            </div>
        </div>

        <div class="card">
            <h2>First Super Admin</h2>
            <div class="grid">
                <div class="field"><label for="admin_username">Username</label><input id="admin_username" name="admin_username" value="<?= installer_e($form['admin_username']) ?>" required></div>
                <div class="field"><label for="admin_display_name">Display Name</label><input id="admin_display_name" name="admin_display_name" value="<?= installer_e($form['admin_display_name']) ?>"></div>
                <div class="field"><label for="admin_email">Email</label><input id="admin_email" name="admin_email" type="email" value="<?= installer_e($form['admin_email']) ?>" required></div>
                <div class="field"><label for="admin_password">Password</label><input id="admin_password" name="admin_password" type="password" required></div>
                <div class="field"><label for="admin_password_confirm">Confirm Password</label><input id="admin_password_confirm" name="admin_password_confirm" type="password" required></div>
            </div>
        </div>

        <div class="actions">
            <button type="submit">Run Installer</button>
        </div>
    </form>
</div>
<script>
  (function () {
    var driverSelect = document.getElementById('db_driver');
    if (!(driverSelect instanceof HTMLSelectElement)) {
      return;
    }

    function syncDriverSections() {
      var selected = driverSelect.value;
      var sections = document.querySelectorAll('[data-driver-section]');
      sections.forEach(function (section) {
        if (!(section instanceof HTMLElement)) {
          return;
        }

        section.style.display = section.getAttribute('data-driver-section') === selected ? 'grid' : 'none';
      });
    }

    driverSelect.addEventListener('change', syncDriverSections);
    syncDriverSections();
  })();
</script>
</body>
</html>
