<?php

/**
 * RAVEN CMS
 * ~/public/install.php
 * One-time installer for initial Raven CMS setup.
 * Docs: https://raven.lanterns.io
 */

// Inline note: This script is intentionally standalone so first-run setup works before full app bootstrap.

declare(strict_types=1);

use Raven\Core\Database\ConnectionFactory;
use Raven\Core\Database\SchemaManager;
use Raven\Repository\GroupRepository;
use Raven\Repository\UserRepository;

/**
 * Escapes text for HTML output.
 */
function installer_e(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
}

/**
 * Persists runtime config to private/dat/config.php with the standard header block.
 *
 * @param array<string, mixed> $config
 */
function installer_write_config(string $path, array $config): void
{
    $export = var_export($config, true);

    $content = "<?php\n\n";
    $content .= "/**\n";
    $content .= " * RAVEN CMS\n";
    $content .= " * ~/private/dat/config.php\n";
    $content .= " * Runtime configuration values for Raven CMS.\n";
    $content .= " * Docs: https://raven.lanterns.io\n";
    $content .= " */\n\n";
    $content .= "// Inline note: Keep site/database defaults explicit so panel config editing stays predictable.\n\n";
    $content .= "declare(strict_types=1);\n\n";
    $content .= "/**\n";
    $content .= " * Raven runtime configuration (generated by installer).\n";
    $content .= " */\n";
    $content .= "return " . $export . ";\n";

    $written = file_put_contents($path, $content, LOCK_EX);
    if ($written === false) {
        throw new RuntimeException('Failed to write private/dat/config.php');
    }
}

/**
 * Returns the mounted base path that contains this installer script.
 */
function installer_base_path(): string
{
    $scriptName = str_replace('\\', '/', (string) ($_SERVER['SCRIPT_NAME'] ?? '/install.php'));
    if ($scriptName === '' || $scriptName[0] !== '/') {
        $scriptName = '/' . ltrim($scriptName, '/');
    }

    $basePath = dirname($scriptName);
    if ($basePath === '.' || $basePath === '/' || $basePath === '\\') {
        return '';
    }

    return rtrim($basePath, '/');
}

/**
 * Returns the install.php path relative to the current mounted base path.
 */
function installer_path(): string
{
    $basePath = installer_base_path();
    return ($basePath !== '' ? $basePath : '') . '/install.php';
}

/**
 * Returns the public root path for the current mounted base path.
 */
function installer_root_path(): string
{
    $basePath = installer_base_path();
    return $basePath !== '' ? ($basePath . '/') : '/';
}

/**
 * Returns one install-session cookie path scoped to this mounted app root.
 */
function installer_session_cookie_path(): string
{
    return installer_root_path();
}

/**
 * Returns one deterministic installer session name scoped to this mounted app.
 */
function installer_session_name(): string
{
    $seed = installer_path();
    if ($seed === '') {
        $seed = '/install.php';
    }

    return 'raven_install_' . substr(sha1($seed), 0, 12);
}

/**
 * Returns true when one directory is writable or can be created by its parent.
 *
 * @return array{ok: bool, detail: string}
 */
function installer_directory_writable_status(string $path): array
{
    if (is_dir($path)) {
        return [
            'ok' => is_writable($path),
            'detail' => is_writable($path)
                ? 'Writable.'
                : 'Directory exists but is not writable by PHP.',
        ];
    }

    $parent = dirname($path);
    if (!is_dir($parent)) {
        return [
            'ok' => false,
            'detail' => 'Parent directory does not exist.',
        ];
    }

    return [
        'ok' => is_writable($parent),
        'detail' => is_writable($parent)
            ? 'Directory does not exist yet, but PHP can create it.'
            : 'Directory does not exist and parent directory is not writable.',
    ];
}

/**
 * Returns true when Composer dependencies appear fully installed.
 *
 * @return array{ok: bool, detail: string}
 */
function installer_composer_install_status(string $root): array
{
    $requiredPaths = [
        $root . '/composer/autoload.php',
        $root . '/composer/composer/installed.php',
        $root . '/composer/delight-im/auth/src/Auth.php',
    ];

    $missing = [];
    foreach ($requiredPaths as $path) {
        if (!is_file($path)) {
            $missing[] = str_replace($root . '/', '', $path);
        }
    }

    if ($missing !== []) {
        return [
            'ok' => false,
            'detail' => 'Missing ' . implode(', ', $missing) . '. Run `composer install`.',
        ];
    }

    return [
        'ok' => true,
        'detail' => 'Composer autoload and installed packages are present.',
    ];
}

/**
 * Returns database driver support flags for installer choices.
 *
 * @return array{sqlite: bool, mysql: bool, pgsql: bool}
 */
function installer_database_driver_support(): array
{
    $pdoLoaded = extension_loaded('pdo');
    $pdoDrivers = $pdoLoaded && class_exists(PDO::class) ? PDO::getAvailableDrivers() : [];

    return [
        'sqlite' => $pdoLoaded && in_array('sqlite', $pdoDrivers, true) && extension_loaded('pdo_sqlite'),
        'mysql' => $pdoLoaded && in_array('mysql', $pdoDrivers, true) && extension_loaded('pdo_mysql'),
        'pgsql' => $pdoLoaded && in_array('pgsql', $pdoDrivers, true) && extension_loaded('pdo_pgsql'),
    ];
}

function installer_default_database_driver(array $driverSupport, string $fallback = 'sqlite'): string
{
    foreach (['sqlite', 'mysql', 'pgsql'] as $driverKey) {
        if (!empty($driverSupport[$driverKey])) {
            return $driverKey;
        }
    }

    return in_array($fallback, ['sqlite', 'mysql', 'pgsql'], true) ? $fallback : 'sqlite';
}

/**
 * Builds installer pre-flight checklist rows.
 *
 * @return array{
 *   rows: array<int, array{
 *     key: string,
 *     label: string,
 *     status: string,
 *     detail: string,
 *     error: string
 *   }>,
 *   has_fail: bool,
 *   fail_count: int,
 *   warn_count: int,
 *   pass_count: int,
 *   summary_label: string,
 *   summary_class: string
 * }
 */
function installer_preflight_checklist(string $root): array
{
    $rows = [];

    $phpVersion = PHP_VERSION;
    if (version_compare($phpVersion, '8.5.0', '>=')) {
        $rows[] = [
            'key' => 'php_version',
            'label' => 'PHP 8.x',
            'status' => 'pass',
            'detail' => 'Running PHP ' . $phpVersion . ' (known-good target met).',
            'error' => '',
        ];
    } elseif (version_compare($phpVersion, '8.0.0', '>=')) {
        $rows[] = [
            'key' => 'php_version',
            'label' => 'PHP 8.x',
            'status' => 'warn',
            'detail' => 'Running PHP ' . $phpVersion . ' (unverified 8.x; may still work).',
            'error' => '',
        ];
    } else {
        $rows[] = [
            'key' => 'php_version',
            'label' => 'PHP 8.x',
            'status' => 'fail',
            'detail' => 'Running PHP ' . $phpVersion . ' (Raven requires PHP 8.x).',
            'error' => 'PHP 8.x is required to run Raven.',
        ];
    }

    $composerStatus = installer_composer_install_status($root);
    $rows[] = [
        'key' => 'composer_install',
        'label' => 'Composer Setup?',
        'status' => $composerStatus['ok'] ? 'pass' : 'fail',
        'detail' => $composerStatus['detail'],
        'error' => $composerStatus['ok'] ? '' : 'Composer dependencies are incomplete. Run `composer install` first.',
    ];

    $pdoLoaded = extension_loaded('pdo');
    $rows[] = [
        'key' => 'pdo',
        'label' => 'PDO Available',
        'status' => $pdoLoaded ? 'pass' : 'fail',
        'detail' => $pdoLoaded ? 'PDO extension is loaded.' : 'PDO extension is missing.',
        'error' => $pdoLoaded ? '' : 'PHP PDO support is required.',
    ];

    $sessionLoaded = extension_loaded('session');
    $rows[] = [
        'key' => 'session',
        'label' => 'Session Support',
        'status' => $sessionLoaded ? 'pass' : 'fail',
        'detail' => $sessionLoaded ? 'Session extension is loaded.' : 'Session extension is missing.',
        'error' => $sessionLoaded ? '' : 'PHP session support is required.',
    ];

    $datStatus = installer_directory_writable_status($root . '/private/dat');
    $rows[] = [
        'key' => 'private_dat',
        'label' => 'Data Directory Writable?',
        'status' => $datStatus['ok'] ? 'pass' : 'fail',
        'detail' => $datStatus['detail'],
        'error' => $datStatus['ok'] ? '' : 'private/dat/ must be writable before install can continue.',
    ];

    $driverSupport = installer_database_driver_support();
    $availableDriverCount = 0;
    foreach ($driverSupport as $isAvailable) {
        if ($isAvailable) {
            $availableDriverCount++;
        }
    }
    $rows[] = [
        'key' => 'database_driver',
        'label' => 'Database Driver',
        'status' => $availableDriverCount > 0 ? 'pass' : 'fail',
        'detail' => 'SQLite: ' . ($driverSupport['sqlite'] ? 'yes' : 'no')
            . ', MySQL: ' . ($driverSupport['mysql'] ? 'yes' : 'no')
            . ', PostgreSQL: ' . ($driverSupport['pgsql'] ? 'yes' : 'no') . '.',
        'error' => $availableDriverCount > 0 ? '' : 'At least one supported database driver must be available.',
    ];

    $gdLoaded = extension_loaded('gd');
    $imagickLoaded = extension_loaded('imagick');
    $imageStatus = $gdLoaded || $imagickLoaded;
    $rows[] = [
        'key' => 'image_processing',
        'label' => 'Image Processing',
        'status' => $imageStatus ? 'pass' : 'fail',
        'detail' => 'GD: ' . ($gdLoaded ? 'yes' : 'no')
            . ', ImageMagick: ' . ($imagickLoaded ? 'yes' : 'no') . '.',
        'error' => $imageStatus ? '' : 'At least one image processing library must be available.',
    ];

    $failCount = 0;
    $warnCount = 0;
    $passCount = 0;
    foreach ($rows as $row) {
        if ($row['status'] === 'fail') {
            $failCount++;
        } elseif ($row['status'] === 'warn') {
            $warnCount++;
        } else {
            $passCount++;
        }
    }

    $summaryLabel = 'Ready';
    $summaryClass = 'pass';
    if ($failCount > 0) {
        $summaryLabel = 'Blocked';
        $summaryClass = 'fail';
    } elseif ($warnCount > 0) {
        $summaryLabel = 'Warnings';
        $summaryClass = 'warn';
    }

    return [
        'rows' => $rows,
        'has_fail' => $failCount > 0,
        'fail_count' => $failCount,
        'warn_count' => $warnCount,
        'pass_count' => $passCount,
        'summary_label' => $summaryLabel,
        'summary_class' => $summaryClass,
    ];
}

/**
 * Starts the installer session with cookie-backed settings only.
 */
function installer_start_session(): void
{
    if (session_status() === PHP_SESSION_ACTIVE) {
        return;
    }

    @ini_set('session.use_cookies', '1');
    @ini_set('session.use_only_cookies', '1');
    @ini_set('session.use_trans_sid', '0');
    @ini_set('session.cookie_domain', '');

    session_name(installer_session_name());
    session_set_cookie_params([
        'lifetime' => 0,
        'path' => installer_session_cookie_path(),
        'secure' => (!empty($_SERVER['HTTPS']) && strtolower((string) $_SERVER['HTTPS']) !== 'off'),
        'httponly' => true,
        'samesite' => 'Lax',
    ]);

    if (@session_start() !== true || session_status() !== PHP_SESSION_ACTIVE || session_id() === '') {
        http_response_code(500);
        echo 'Installer session could not be started. Check PHP session cookie settings and session storage.';
        exit;
    }
}

$root = dirname(__DIR__);
$configPath = $root . '/private/dat/config.php';
$configTemplatePath = $root . '/private/dat/config.php.dist';
$extensionStatePath = $root . '/private/dat/ext/.state.php';
$extensionStateTemplatePath = $root . '/private/dat/ext/.state.php.dist';
$lockPath = $root . '/private/dat/install.lock';
$sqliteDefaultBasePath = rtrim($root, '/') . '/private/dat/db.sqlite';
$installerPath = installer_path();
$installerRootPath = installer_root_path();

$detectedDomain = strtolower(trim((string) ($_SERVER['HTTP_HOST'] ?? $_SERVER['SERVER_NAME'] ?? '')));
if ($detectedDomain !== '') {
    if (str_contains($detectedDomain, ',')) {
        $detectedDomain = trim((string) explode(',', $detectedDomain, 2)[0]);
    }

    if (str_starts_with($detectedDomain, '[')) {
        $closingBracketPos = strpos($detectedDomain, ']');
        if ($closingBracketPos !== false) {
            $detectedDomain = substr($detectedDomain, 1, $closingBracketPos - 1);
        }
    } else {
        $lastColonPos = strrpos($detectedDomain, ':');
        if ($lastColonPos !== false && substr_count($detectedDomain, ':') === 1) {
            $maybePort = substr($detectedDomain, $lastColonPos + 1);
            if ($maybePort !== '' && ctype_digit($maybePort)) {
                $detectedDomain = substr($detectedDomain, 0, $lastColonPos);
            }
        }
    }

    $detectedDomain = rtrim($detectedDomain, '.');
}

// Installer lock is checked first to keep re-entry behavior deterministic.
if (is_file($lockPath)) {
    header('Location: ' . $installerRootPath, true, 302);
    exit;
}

// Bring in Composer dependencies first; fallback autoloader keeps local classes available pre-install.
$composerAutoload = $root . '/composer/autoload.php';
if (is_file($composerAutoload)) {
    // Match runtime bootstrap behavior so EasyMDE's PHP bridge is not auto-loaded during install.
    $composerAutoloadFiles = $root . '/composer/composer/autoload_files.php';
    if (is_file($composerAutoloadFiles)) {
        /** @var mixed $autoloadFiles */
        $autoloadFiles = require $composerAutoloadFiles;
        if (is_array($autoloadFiles)) {
            if (!isset($GLOBALS['__composer_autoload_files']) || !is_array($GLOBALS['__composer_autoload_files'])) {
                $GLOBALS['__composer_autoload_files'] = [];
            }

            foreach ($autoloadFiles as $fileIdentifier => $filePath) {
                $normalizedPath = str_replace('\\', '/', (string) $filePath);
                if (str_contains($normalizedPath, '/tualo/easymde/src/functions.php')) {
                    $GLOBALS['__composer_autoload_files'][(string) $fileIdentifier] = true;
                }
            }
        }
    }

    require_once $composerAutoload;
}

spl_autoload_register(static function (string $class) use ($root): void {
    $prefix = 'Raven\\';
    if (!str_starts_with($class, $prefix)) {
        return;
    }

    $relative = str_replace('\\', '/', substr($class, strlen($prefix)));
    $path = $root . '/private/sys/' . $relative . '.php';
    if (is_file($path)) {
        require_once $path;
    }
});

// Session-backed CSRF token protects this high-impact setup endpoint.
installer_start_session();

if (!isset($_SESSION['_raven_install_csrf']) || !is_string($_SESSION['_raven_install_csrf'])) {
    $_SESSION['_raven_install_csrf'] = bin2hex(random_bytes(32));
}
$csrfToken = (string) $_SESSION['_raven_install_csrf'];
$sessionCookieName = session_name();
$hasInstallerSessionCookie = isset($_COOKIE[$sessionCookieName])
    && is_string($_COOKIE[$sessionCookieName])
    && trim((string) $_COOKIE[$sessionCookieName]) !== '';

/** @var mixed $rawTemplate */
$rawTemplate = is_file($configTemplatePath) ? require $configTemplatePath : [];
$template = is_array($rawTemplate) ? $rawTemplate : [];

/** @var mixed $rawExisting */
$rawExisting = is_file($configPath) ? require $configPath : [];
$existing = is_array($rawExisting) ? $rawExisting : [];

$defaultConfig = $existing !== [] ? $existing : $template;
$defaultSiteDomain = trim((string) ($defaultConfig['site']['domain'] ?? ''));
if ($defaultSiteDomain === '') {
    $defaultSiteDomain = $detectedDomain;
}
$defaultTablePrefix = trim((string) ($defaultConfig['database']['prefix'] ?? ($defaultConfig['database']['table_prefix'] ?? '')));
if ($defaultTablePrefix === '') {
    $defaultTablePrefix = 'rvn_';
}
if ($existing === [] && strtolower($defaultTablePrefix) === 'raven_') {
    $defaultTablePrefix = 'rvn_';
}
$configuredDefaultDriver = strtolower(trim((string) ($defaultConfig['database']['driver'] ?? 'sqlite')));
if (!in_array($configuredDefaultDriver, ['sqlite', 'mysql', 'pgsql'], true)) {
    $configuredDefaultDriver = 'sqlite';
}
$driverSupport = installer_database_driver_support();
$defaultDriver = installer_default_database_driver($driverSupport, $configuredDefaultDriver);
$driverLabels = [
    'sqlite' => 'SQLite',
    'mysql' => 'MySQL / MariaDB',
    'pgsql' => 'PostgreSQL',
];
$defaultSiteName = trim((string) ($defaultConfig['site']['name'] ?? 'Raven CMS'));
if ($defaultSiteName === '') {
    $defaultSiteName = 'Raven CMS';
}
$defaultPanelPath = trim((string) ($defaultConfig['panel']['path'] ?? 'panel'));
if ($defaultPanelPath === '') {
    $defaultPanelPath = 'panel';
}

// Keep form values empty on first render so placeholders can guide typing without manual clearing.
$form = [
    'site_domain' => '',
    'site_name' => '',
    'panel_path' => '',
    'db_driver' => $defaultDriver,
    'db_table_prefix' => '',
    'mysql_host' => '',
    'mysql_port' => '',
    'mysql_dbname' => '',
    'mysql_user' => '',
    'mysql_password' => '',
    'mysql_charset' => '',
    'pgsql_host' => '',
    'pgsql_port' => '',
    'pgsql_dbname' => '',
    'pgsql_user' => '',
    'pgsql_password' => '',
    'enable_usernames' => '',
    'admin_username' => '',
    'admin_display_name' => '',
    'admin_email' => '',
    'admin_password' => '',
    'admin_password_confirm' => '',
];
$formPlaceholders = [
    'site_domain' => $defaultSiteDomain !== '' ? $defaultSiteDomain : 'example.com',
    'site_name' => $defaultSiteName,
    'panel_path' => $defaultPanelPath,
    'db_table_prefix' => $defaultTablePrefix,
    'mysql_host' => trim((string) ($defaultConfig['database']['mysql']['host'] ?? '127.0.0.1')),
    'mysql_port' => trim((string) ($defaultConfig['database']['mysql']['port'] ?? '3306')),
    'mysql_dbname' => trim((string) ($defaultConfig['database']['mysql']['name'] ?? ($defaultConfig['database']['mysql']['dbname'] ?? 'raven'))),
    'mysql_user' => trim((string) ($defaultConfig['database']['mysql']['user'] ?? 'raven')),
    'mysql_charset' => trim((string) ($defaultConfig['database']['mysql']['charset'] ?? 'utf8mb4')),
    'pgsql_host' => trim((string) ($defaultConfig['database']['pgsql']['host'] ?? '127.0.0.1')),
    'pgsql_port' => trim((string) ($defaultConfig['database']['pgsql']['port'] ?? '5432')),
    'pgsql_dbname' => trim((string) ($defaultConfig['database']['pgsql']['name'] ?? ($defaultConfig['database']['pgsql']['dbname'] ?? 'raven'))),
    'pgsql_user' => trim((string) ($defaultConfig['database']['pgsql']['user'] ?? 'raven')),
    'admin_username' => 'optional',
    'admin_display_name' => 'Admin',
    'admin_email' => 'admin@example.com',
];

$errors = [];
$isPost = strtoupper((string) ($_SERVER['REQUEST_METHOD'] ?? 'GET')) === 'POST';

if ($isPost) {
    foreach ($form as $key => $_) {
        $form[$key] = trim((string) ($_POST[$key] ?? ''));
    }
}

$preflight = installer_preflight_checklist($root);

if ($isPost) {
    foreach ($preflight['rows'] as $preflightRow) {
        if (($preflightRow['status'] ?? '') !== 'fail') {
            continue;
        }

        $message = trim((string) ($preflightRow['error'] ?? ''));
        if ($message !== '') {
            $errors[] = $message;
        }
    }

    if (!$hasInstallerSessionCookie) {
        $errors[] = 'Installer session cookie was not returned by the browser. Check PHP session cookie settings, proxy cookie rewriting, and session storage.';
    } elseif (!hash_equals($csrfToken, (string) ($_POST['_csrf'] ?? ''))) {
        $errors[] = 'Invalid form token. Reload the page and try again.';
    }

    $driver = strtolower($form['db_driver']);
    if (!in_array($driver, ['sqlite', 'mysql', 'pgsql'], true)) {
        $errors[] = 'Database driver must be sqlite, mysql, or pgsql.';
    } elseif (empty($driverSupport[$driver])) {
        $errors[] = ($driverLabels[$driver] ?? ucfirst($driver)) . ' support is not available on this PHP build.';
    }

    $siteDomain = $form['site_domain'] !== '' ? $form['site_domain'] : $formPlaceholders['site_domain'];
    $siteName = $form['site_name'] !== '' ? $form['site_name'] : $formPlaceholders['site_name'];
    $panelPathSource = $form['panel_path'] !== '' ? $form['panel_path'] : $formPlaceholders['panel_path'];
    $panelPath = strtolower($panelPathSource);

    if ($siteDomain === '') {
        $errors[] = 'Site domain is required.';
    }
    if ($siteName === '') {
        $errors[] = 'Site name is required.';
    }
    if ($panelPath === '' || preg_match('/^[a-z0-9][a-z0-9_-]*$/', $panelPath) !== 1) {
        $errors[] = 'Panel path must contain only lowercase letters, numbers, underscores, or dashes.';
    }

    $tablePrefixSource = $form['db_table_prefix'] !== '' ? $form['db_table_prefix'] : $formPlaceholders['db_table_prefix'];
    $tablePrefix = preg_replace('/[^a-zA-Z0-9_]/', '', $tablePrefixSource) ?? '';
    if ($driver === 'sqlite') {
        $sqliteBasePath = $sqliteDefaultBasePath;
    } else {
        $sqliteBasePath = $sqliteDefaultBasePath;
    }

    $mysqlHost = $form['mysql_host'] !== '' ? $form['mysql_host'] : $formPlaceholders['mysql_host'];
    $mysqlPortRaw = $form['mysql_port'] !== '' ? $form['mysql_port'] : $formPlaceholders['mysql_port'];
    $mysqlPort = (int) $mysqlPortRaw;
    $mysqlDbName = $form['mysql_dbname'] !== '' ? $form['mysql_dbname'] : $formPlaceholders['mysql_dbname'];
    $mysqlUser = $form['mysql_user'] !== '' ? $form['mysql_user'] : $formPlaceholders['mysql_user'];
    $mysqlCharset = $form['mysql_charset'] !== '' ? $form['mysql_charset'] : $formPlaceholders['mysql_charset'];
    if ($driver === 'mysql') {
        if ($mysqlHost === '' || $mysqlDbName === '' || $mysqlUser === '') {
            $errors[] = 'MySQL host, database, and user are required.';
        }
        if ($mysqlPort < 1 || $mysqlPort > 65535) {
            $errors[] = 'MySQL port must be between 1 and 65535.';
        }
        if ($mysqlCharset === '') {
            $errors[] = 'MySQL charset is required.';
        }
    }

    $pgsqlHost = $form['pgsql_host'] !== '' ? $form['pgsql_host'] : $formPlaceholders['pgsql_host'];
    $pgsqlPortRaw = $form['pgsql_port'] !== '' ? $form['pgsql_port'] : $formPlaceholders['pgsql_port'];
    $pgsqlPort = (int) $pgsqlPortRaw;
    $pgsqlDbName = $form['pgsql_dbname'] !== '' ? $form['pgsql_dbname'] : $formPlaceholders['pgsql_dbname'];
    $pgsqlUser = $form['pgsql_user'] !== '' ? $form['pgsql_user'] : $formPlaceholders['pgsql_user'];
    if ($driver === 'pgsql') {
        if ($pgsqlHost === '' || $pgsqlDbName === '' || $pgsqlUser === '') {
            $errors[] = 'PostgreSQL host, database, and user are required.';
        }
        if ($pgsqlPort < 1 || $pgsqlPort > 65535) {
            $errors[] = 'PostgreSQL port must be between 1 and 65535.';
        }
    }

    $enableUsernames = (string) ($form['enable_usernames'] ?? '') === '1';
    $adminUsername = $enableUsernames ? $form['admin_username'] : '';
    $adminDisplayName = $form['admin_display_name'] !== ''
        ? $form['admin_display_name']
        : $formPlaceholders['admin_display_name'];
    $adminEmail = $form['admin_email'] !== '' ? $form['admin_email'] : $formPlaceholders['admin_email'];
    $adminPassword = $form['admin_password'];
    $adminPasswordConfirm = $form['admin_password_confirm'];

    if ($enableUsernames && preg_match('/^[a-zA-Z0-9_.-]{3,100}$/', $adminUsername) !== 1) {
        $errors[] = 'Admin username is required and must be 3-100 characters using letters, numbers, dot, underscore, or dash.';
    }
    if ($adminEmail === '' || filter_var($adminEmail, FILTER_VALIDATE_EMAIL) === false) {
        $errors[] = 'A valid admin email is required.';
    }
    if ($adminDisplayName === '') {
        $adminDisplayName = $adminEmail;
    }
    if (strlen($adminPassword) < 8) {
        $errors[] = 'Admin password must be at least 8 characters.';
    }
    if (!hash_equals($adminPassword, $adminPasswordConfirm)) {
        $errors[] = 'Admin password confirmation does not match.';
    }

    if ($errors === []) {
        $nextConfig = is_array($template) && $template !== [] ? $template : [];

        // Keep installer output aligned with panel config editor expectations.
        $nextConfig['site'] = [
            'protocol' => trim((string) ($nextConfig['site']['protocol'] ?? 'https')) !== ''
                ? trim((string) ($nextConfig['site']['protocol'] ?? 'https'))
                : 'https',
            'domain' => $siteDomain,
            'name' => $siteName,
            'visibility' => 'public',
            'theme' => trim((string) ($nextConfig['site']['theme'] ?? 'raven')) !== ''
                ? trim((string) ($nextConfig['site']['theme'] ?? 'raven'))
                : 'raven',
        ];

        $nextConfig['panel'] = is_array($nextConfig['panel'] ?? null) ? $nextConfig['panel'] : [];
        $nextConfig['panel']['path'] = $panelPath;
        if (!array_key_exists('theme', $nextConfig['panel'])) {
            $nextConfig['panel']['theme'] = 'corp';
        }
        if (!array_key_exists('brand_name', $nextConfig['panel'])) {
            $nextConfig['panel']['brand_name'] = $siteName;
        }
        if (!array_key_exists('brand_logo', $nextConfig['panel'])) {
            $nextConfig['panel']['brand_logo'] = '';
        }
        unset($nextConfig['public']);
        $nextConfig['user'] = is_array($nextConfig['user'] ?? null) ? $nextConfig['user'] : [];
        $nextConfig['user']['auth'] = is_array($nextConfig['user']['auth'] ?? null) ? $nextConfig['user']['auth'] : [];
        $nextConfig['user']['auth']['method'] = $enableUsernames ? 'username' : 'email';
        $nextConfig['user']['auth']['registration'] = 'closed';

        $nextConfig['database'] = [
            'driver' => $driver,
            'sqlite' => [
                'path' => $sqliteBasePath,
            ],
            'mysql' => [
                'host' => $mysqlHost,
                'port' => $mysqlPort > 0 ? $mysqlPort : 3306,
                'name' => $mysqlDbName,
                'user' => $mysqlUser,
                'pass' => $form['mysql_password'],
                'charset' => $mysqlCharset !== '' ? $mysqlCharset : 'utf8mb4',
            ],
            'pgsql' => [
                'host' => $pgsqlHost,
                'port' => $pgsqlPort > 0 ? $pgsqlPort : 5432,
                'name' => $pgsqlDbName,
                'user' => $pgsqlUser,
                'pass' => $form['pgsql_password'],
            ],
            'prefix' => $tablePrefix,
        ];

        // Installer replaces bootstrap seeding; remove any legacy key entirely.
        unset($nextConfig['bootstrap_admin']);

        try {
            // Create SQLite storage directory only when SQLite is selected during install.
            if ($driver === 'sqlite') {
                $sqliteDirectory = dirname($sqliteBasePath);
                if (!is_dir($sqliteDirectory) && !mkdir($sqliteDirectory, 0775, true) && !is_dir($sqliteDirectory)) {
                    throw new RuntimeException('Failed to create SQLite base path directory.');
                }
            }

            $connectionFactory = new ConnectionFactory((array) ($nextConfig['database'] ?? []));
            $driverName = $connectionFactory->getDriver();
            $prefix = $connectionFactory->getPrefix();

            $rvnDb = $connectionFactory->createAppConnection();
            $authDb = $connectionFactory->createAuthConnection();

            $schema = new SchemaManager();
            $schema->ensure($rvnDb, $authDb, $driverName, $prefix);

            $users = new UserRepository($authDb, $rvnDb, $driverName, $prefix);
            if ($users->listAll() !== []) {
                throw new RuntimeException('Installer can only create the initial admin on an empty user database.');
            }

            $groups = new GroupRepository($rvnDb, $driverName, $prefix);

            // Raven now uses the canonical `admin` stock group for the first installed operator.
            // The legacy `super` slug no longer exists in fresh installs.
            $adminGroupId = $groups->idBySlug('admin');
            if ($adminGroupId === null) {
                throw new RuntimeException('Stock admin group was not created correctly.');
            }

            $users->save([
                'id' => null,
                'username' => $adminUsername,
                'display_name' => $adminDisplayName,
                'email' => $adminEmail,
                'theme' => 'default',
                'password' => $adminPassword,
                'group_ids' => [$adminGroupId],
                'string_length' => (int) (($nextConfig['user']['string'] ?? 28)),
            ]);

            installer_write_config($configPath, $nextConfig);

            // Seed runtime extension state from committed defaults template.
            if (!is_file($extensionStateTemplatePath)) {
                throw new RuntimeException('Missing extension state template private/dat/ext/.state.php.dist.');
            }

            $stateTemplateContent = file_get_contents($extensionStateTemplatePath);
            if ($stateTemplateContent === false || trim($stateTemplateContent) === '') {
                throw new RuntimeException('Extension state template is unreadable or empty.');
            }

            $stateDirectory = dirname($extensionStatePath);
            if (!is_dir($stateDirectory) && !mkdir($stateDirectory, 0775, true) && !is_dir($stateDirectory)) {
                throw new RuntimeException('Failed to create extension state directory.');
            }

            if (file_put_contents($extensionStatePath, $stateTemplateContent, LOCK_EX) === false) {
                throw new RuntimeException('Failed to write private/dat/ext/.state.php.');
            }

            $lockDirectory = dirname($lockPath);
            if (!is_dir($lockDirectory) && !mkdir($lockDirectory, 0775, true) && !is_dir($lockDirectory)) {
                throw new RuntimeException('Failed to create installer lock directory.');
            }

            $lockContent = "Raven CMS installer lock\nInstalled at (UTC): " . gmdate('c') . "\n";
            if (file_put_contents($lockPath, $lockContent, LOCK_EX) === false) {
                throw new RuntimeException('Failed to write installer lock file.');
            }

            $panelRedirectPath = ($installerRootPath !== '/' ? rtrim($installerRootPath, '/') : '') . '/' . ltrim($panelPath, '/');
            header('Location: ' . $panelRedirectPath, true, 302);
            exit;
        } catch (\Throwable $exception) {
            $errors[] = 'Installation failed: ' . $exception->getMessage();
        }
    }
}
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Raven CMS Installer</title>
    <style>
        body { font-family: sans-serif; background: #f4f6f8; color: #1a1f24; margin: 0; }
        .wrap { max-width: 920px; margin: 2rem auto; padding: 0 1rem 2rem; }
        .card { background: #fff; border: 1px solid #d7dde5; border-radius: 8px; padding: 1.25rem; margin-bottom: 1rem; }
        h1, h2 { margin: 0 0 0.8rem; }
        h1 { font-size: 1.45rem; }
        h2 { font-size: 1.05rem; border-bottom: 1px solid #edf1f5; padding-bottom: 0.45rem; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0.85rem 1rem; }
        .field { display: flex; flex-direction: column; gap: 0.3rem; }
        .field.full { grid-column: 1 / -1; }
        label { font-size: 0.9rem; font-weight: 600; }
        input, select { border: 1px solid #b8c3d1; border-radius: 6px; padding: 0.5rem 0.55rem; font-size: 0.95rem; }
        input::placeholder { color: #7d8998; opacity: 1; }
        .note { font-size: 0.86rem; color: #4d5b6b; margin-top: 0.25rem; }
        .alert { border-radius: 6px; padding: 0.8rem 0.9rem; margin-bottom: 1rem; }
        .alert.error { background: #fcebec; border: 1px solid #f3b4b8; color: #7a1f26; }
        .preflight-summary { display: flex; align-items: center; justify-content: space-between; gap: 1rem; flex-wrap: wrap; margin-bottom: 1rem; }
        .preflight-summary-meta { font-size: 0.86rem; color: #4d5b6b; }
        .preflight-list { list-style: none; padding: 0; margin: 0; display: grid; gap: 0.7rem; }
        .preflight-item { border: 1px solid #d7dde5; border-radius: 6px; padding: 0.8rem 0.9rem; }
        .preflight-item.is-pass { border-color: #bfdcc4; background: #f4fbf5; }
        .preflight-item.is-warn { border-color: #eed9a2; background: #fff9e8; }
        .preflight-item.is-fail { border-color: #f0b7bc; background: #fff2f3; }
        .preflight-row { display: flex; align-items: flex-start; justify-content: space-between; gap: 1rem; }
        .preflight-label { font-weight: 600; font-size: 0.95rem; }
        .preflight-detail { color: #4d5b6b; font-size: 0.86rem; margin-top: 0.2rem; }
        .status-badge { display: inline-flex; align-items: center; border-radius: 999px; padding: 0.18rem 0.58rem; font-size: 0.76rem; font-weight: 700; white-space: nowrap; }
        .status-badge.pass { background: #d8f0dc; color: #1f6a2b; }
        .status-badge.warn { background: #f9ebbb; color: #7a5a00; }
        .status-badge.fail { background: #f8d7da; color: #8a1f2d; }
        .actions { display: flex; justify-content: flex-end; margin-top: 1rem; }
        button { background: #154f95; color: #fff; border: 0; border-radius: 6px; padding: 0.62rem 1rem; font-size: 0.95rem; cursor: pointer; }
        button:hover { background: #123f77; }
        [data-driver-section] { display: none; }
        @media (max-width: 800px) {
            .grid { grid-template-columns: 1fr; }
            .preflight-row { flex-direction: column; align-items: flex-start; }
        }
    </style>
</head>
<body>
<div class="wrap">
    <div class="card">
        <h1>Raven CMS Installer</h1>
    </div>

    <div class="card">
        <h2>Pre-Flight Checklist</h2>
        <div class="preflight-summary">
            <div>
                <span
                    class="status-badge <?= installer_e((string) $preflight['summary_class']) ?>"
                    id="preflight-summary-badge"
                ><?= installer_e((string) $preflight['summary_label']) ?></span>
            </div>
            <div class="preflight-summary-meta" id="preflight-summary-meta">
                <?= installer_e((string) $preflight['pass_count']) ?> pass,
                <?= installer_e((string) $preflight['warn_count']) ?> warning<?= (int) $preflight['warn_count'] === 1 ? '' : 's' ?>,
                <?= installer_e((string) $preflight['fail_count']) ?> blocking issue<?= (int) $preflight['fail_count'] === 1 ? '' : 's' ?>
            </div>
        </div>
        <ul class="preflight-list" id="preflight-list">
            <?php foreach ($preflight['rows'] as $row): ?>
                <?php
                $rowKey = (string) ($row['key'] ?? '');
                $rowStatus = (string) ($row['status'] ?? 'warn');
                $rowLabel = (string) ($row['label'] ?? $rowKey);
                $rowDetail = (string) ($row['detail'] ?? '');
                ?>
                <li
                    class="preflight-item is-<?= installer_e($rowStatus) ?>"
                    data-preflight-item="1"
                    data-preflight-status="<?= installer_e($rowStatus) ?>"
                >
                    <div class="preflight-row">
                        <div>
                            <div class="preflight-label"><?= installer_e($rowLabel) ?></div>
                            <div class="preflight-detail" data-preflight-detail="1"><?= installer_e($rowDetail) ?></div>
                        </div>
                        <span class="status-badge <?= installer_e($rowStatus) ?>" data-preflight-badge="1">
                            <?= installer_e(match ($rowStatus) {
                                'pass' => 'Pass',
                                'warn' => 'Warn',
                                default => 'Fail',
                            }) ?>
                        </span>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <?php if ($errors !== []): ?>
        <div class="alert error">
            <strong>Install could not complete.</strong>
            <ul>
                <?php foreach ($errors as $error): ?>
                    <li><?= installer_e($error) ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <form method="post" action="<?= installer_e($installerPath) ?>" novalidate>
        <input type="hidden" name="_csrf" value="<?= installer_e($csrfToken) ?>">

        <div class="card">
            <h2>Site</h2>
            <div class="grid">
                <div class="field">
                    <label for="site_domain">Domain</label>
                    <input id="site_domain" name="site_domain" value="<?= installer_e($form['site_domain']) ?>" placeholder="<?= installer_e($formPlaceholders['site_domain']) ?>" required>
                    <div class="note">Example: <code>example.com</code></div>
                </div>
                <div class="field">
                    <label for="site_name">Site Name</label>
                    <input id="site_name" name="site_name" value="<?= installer_e($form['site_name']) ?>" placeholder="<?= installer_e($formPlaceholders['site_name']) ?>" required>
                </div>
                <div class="field">
                    <label for="panel_path">Panel Path</label>
                    <input id="panel_path" name="panel_path" value="<?= installer_e($form['panel_path']) ?>" placeholder="<?= installer_e($formPlaceholders['panel_path']) ?>" required>
                    <div class="note">Example: <code>panel</code> for <code>/panel</code></div>
                </div>
            </div>
        </div>

        <div class="card">
            <h2>Database</h2>
            <div class="grid">
                <div class="field">
                    <label for="db_driver">Driver</label>
                    <select id="db_driver" name="db_driver" required>
                        <?php foreach ($driverLabels as $driverKey => $driverLabel): ?>
                            <option
                                value="<?= installer_e($driverKey) ?>"
                                <?= $form['db_driver'] === $driverKey ? ' selected' : '' ?>
                                <?= !($driverSupport[$driverKey] ?? false) ? ' disabled' : '' ?>
                            ><?= installer_e($driverLabel) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="field" id="db_table_prefix_field">
                    <label for="db_table_prefix">Table Prefix (MySQL/PostgreSQL)</label>
                    <input id="db_table_prefix" name="db_table_prefix" value="<?= installer_e($form['db_table_prefix']) ?>" placeholder="<?= installer_e($formPlaceholders['db_table_prefix']) ?>">
                </div>
            </div>

            <div class="grid" data-driver-section="sqlite">
                <div class="field full">
                    <label>SQLite Storage</label>
                    <div class="note">SQLite core data is stored automatically in <code>private/dat/db.sqlite</code>.</div>
                </div>
            </div>

            <div class="grid" data-driver-section="mysql">
                <div class="field"><label for="mysql_host">MySQL Host</label><input id="mysql_host" name="mysql_host" value="<?= installer_e($form['mysql_host']) ?>" placeholder="<?= installer_e($formPlaceholders['mysql_host']) ?>"></div>
                <div class="field"><label for="mysql_port">MySQL Port</label><input id="mysql_port" name="mysql_port" value="<?= installer_e($form['mysql_port']) ?>" placeholder="<?= installer_e($formPlaceholders['mysql_port']) ?>"></div>
                <div class="field"><label for="mysql_dbname">MySQL Database</label><input id="mysql_dbname" name="mysql_dbname" value="<?= installer_e($form['mysql_dbname']) ?>" placeholder="<?= installer_e($formPlaceholders['mysql_dbname']) ?>"></div>
                <div class="field"><label for="mysql_user">MySQL User</label><input id="mysql_user" name="mysql_user" value="<?= installer_e($form['mysql_user']) ?>" placeholder="<?= installer_e($formPlaceholders['mysql_user']) ?>"></div>
                <div class="field"><label for="mysql_password">MySQL Password</label><input id="mysql_password" name="mysql_password" type="password" value="<?= installer_e($form['mysql_password']) ?>"></div>
                <div class="field"><label for="mysql_charset">MySQL Charset</label><input id="mysql_charset" name="mysql_charset" value="<?= installer_e($form['mysql_charset']) ?>" placeholder="<?= installer_e($formPlaceholders['mysql_charset']) ?>"></div>
            </div>

            <div class="grid" data-driver-section="pgsql">
                <div class="field"><label for="pgsql_host">PostgreSQL Host</label><input id="pgsql_host" name="pgsql_host" value="<?= installer_e($form['pgsql_host']) ?>" placeholder="<?= installer_e($formPlaceholders['pgsql_host']) ?>"></div>
                <div class="field"><label for="pgsql_port">PostgreSQL Port</label><input id="pgsql_port" name="pgsql_port" value="<?= installer_e($form['pgsql_port']) ?>" placeholder="<?= installer_e($formPlaceholders['pgsql_port']) ?>"></div>
                <div class="field"><label for="pgsql_dbname">PostgreSQL Database</label><input id="pgsql_dbname" name="pgsql_dbname" value="<?= installer_e($form['pgsql_dbname']) ?>" placeholder="<?= installer_e($formPlaceholders['pgsql_dbname']) ?>"></div>
                <div class="field"><label for="pgsql_user">PostgreSQL User</label><input id="pgsql_user" name="pgsql_user" value="<?= installer_e($form['pgsql_user']) ?>" placeholder="<?= installer_e($formPlaceholders['pgsql_user']) ?>"></div>
                <div class="field"><label for="pgsql_password">PostgreSQL Password</label><input id="pgsql_password" name="pgsql_password" type="password" value="<?= installer_e($form['pgsql_password']) ?>"></div>
            </div>
        </div>

        <div class="card">
            <h2>First Admin</h2>
            <div class="grid">
                <div class="field full">
                    <label for="enable_usernames" style="display:flex;align-items:center;gap:0.45rem;">
                        <input id="enable_usernames" name="enable_usernames" type="checkbox" value="1"<?= (string) ($form['enable_usernames'] ?? '') === '1' ? ' checked' : '' ?>>
                        <span>Enable usernames for panel login</span>
                    </label>
                    <div class="note">When enabled, login mode is set to username and an admin username is required.</div>
                </div>
                <div class="field" id="admin_username_field"<?= (string) ($form['enable_usernames'] ?? '') === '1' ? '' : ' style="display:none;"' ?>>
                    <label for="admin_username">Username</label>
                    <input
                        id="admin_username"
                        name="admin_username"
                        value="<?= installer_e($form['admin_username']) ?>"
                        placeholder="<?= installer_e($formPlaceholders['admin_username']) ?>"
                        <?= (string) ($form['enable_usernames'] ?? '') === '1' ? 'required' : 'disabled' ?>
                    >
                    <div class="note">Used as the panel login identifier when usernames are enabled.</div>
                </div>
                <div class="field"><label for="admin_display_name">Display Name</label><input id="admin_display_name" name="admin_display_name" value="<?= installer_e($form['admin_display_name']) ?>" placeholder="<?= installer_e($formPlaceholders['admin_display_name']) ?>"></div>
                <div class="field"><label for="admin_email">Email</label><input id="admin_email" name="admin_email" type="email" value="<?= installer_e($form['admin_email']) ?>" placeholder="<?= installer_e($formPlaceholders['admin_email']) ?>" required></div>
                <div class="field"><label for="admin_password">Password</label><input id="admin_password" name="admin_password" type="password" required></div>
                <div class="field"><label for="admin_password_confirm">Confirm Password</label><input id="admin_password_confirm" name="admin_password_confirm" type="password" required></div>
            </div>
        </div>

        <div class="actions">
            <button type="submit">Run Installer</button>
        </div>
    </form>
</div>
<script>
  (function () {
    var driverSelect = document.getElementById('db_driver');
    if (!(driverSelect instanceof HTMLSelectElement)) {
      return;
    }
    var tablePrefixField = document.getElementById('db_table_prefix_field');
    var tablePrefixInput = document.getElementById('db_table_prefix');
    var enableUsernamesInput = document.getElementById('enable_usernames');
    var adminUsernameField = document.getElementById('admin_username_field');
    var adminUsernameInput = document.getElementById('admin_username');

    function syncDriverSections() {
      var selected = driverSelect.value;
      var sections = document.querySelectorAll('[data-driver-section]');
      sections.forEach(function (section) {
        if (!(section instanceof HTMLElement)) {
          return;
        }

        section.style.display = section.getAttribute('data-driver-section') === selected ? 'grid' : 'none';
      });

      if (tablePrefixField instanceof HTMLElement) {
        tablePrefixField.style.display = selected === 'sqlite' ? 'none' : '';
      }
      if (tablePrefixInput instanceof HTMLInputElement) {
        tablePrefixInput.disabled = selected === 'sqlite';
      }
    }

    driverSelect.addEventListener('change', syncDriverSections);
    syncDriverSections();

    function syncUsernameFields() {
      var enabled = enableUsernamesInput instanceof HTMLInputElement && enableUsernamesInput.checked;
      if (adminUsernameField instanceof HTMLElement) {
        adminUsernameField.style.display = enabled ? '' : 'none';
      }
      if (adminUsernameInput instanceof HTMLInputElement) {
        adminUsernameInput.disabled = !enabled;
        adminUsernameInput.required = enabled;
      }
    }

    if (enableUsernamesInput instanceof HTMLInputElement) {
      enableUsernamesInput.addEventListener('change', syncUsernameFields);
    }
    syncUsernameFields();
  })();
</script>
</body>
</html>
