<?php

/**
 * RAVEN CMS
 * ~/public/install.php
 * One-time installer for initial Raven CMS setup.
 * Docs: https://raven.lanterns.io
 */

// Inline note: This script is intentionally standalone so first-run setup works before full app bootstrap.

declare(strict_types=1);

use Raven\Core\Database\ConnectionFactory;
use Raven\Core\Database\SchemaManager;
use Raven\Repository\GroupRepository;
use Raven\Repository\UserRepository;

/**
 * Escapes text for HTML output.
 */
function installer_e(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
}

/**
 * Persists runtime config to private/config.php with the standard header block.
 *
 * @param array<string, mixed> $config
 */
function installer_write_config(string $path, array $config): void
{
    $export = var_export($config, true);

    $content = "<?php\n\n";
    $content .= "/**\n";
    $content .= " * RAVEN CMS\n";
    $content .= " * ~/private/config.php\n";
    $content .= " * Runtime configuration values for Raven CMS.\n";
    $content .= " * Docs: https://raven.lanterns.io\n";
    $content .= " */\n\n";
    $content .= "// Inline note: Keep site/database defaults explicit so panel config editing stays predictable.\n\n";
    $content .= "declare(strict_types=1);\n\n";
    $content .= "/**\n";
    $content .= " * Raven runtime configuration (generated by installer).\n";
    $content .= " */\n";
    $content .= "return " . $export . ";\n";

    $written = file_put_contents($path, $content, LOCK_EX);
    if ($written === false) {
        throw new RuntimeException('Failed to write private/config.php');
    }
}

$root = dirname(__DIR__);
$configPath = $root . '/private/config.php';
$configTemplatePath = $root . '/private/config.php.dist';
$extensionStatePath = $root . '/private/dat/ext/.state.php';
$extensionStateTemplatePath = $root . '/private/dat/ext/.state.php.dist';
$lockPath = $root . '/private/dat/install.lock';
$sqliteDefaultBasePath = rtrim($root, '/') . '/private/dat/db';

$detectedDomain = strtolower(trim((string) ($_SERVER['HTTP_HOST'] ?? $_SERVER['SERVER_NAME'] ?? '')));
if ($detectedDomain !== '') {
    if (str_contains($detectedDomain, ',')) {
        $detectedDomain = trim((string) explode(',', $detectedDomain, 2)[0]);
    }

    if (str_starts_with($detectedDomain, '[')) {
        $closingBracketPos = strpos($detectedDomain, ']');
        if ($closingBracketPos !== false) {
            $detectedDomain = substr($detectedDomain, 1, $closingBracketPos - 1);
        }
    } else {
        $lastColonPos = strrpos($detectedDomain, ':');
        if ($lastColonPos !== false && substr_count($detectedDomain, ':') === 1) {
            $maybePort = substr($detectedDomain, $lastColonPos + 1);
            if ($maybePort !== '' && ctype_digit($maybePort)) {
                $detectedDomain = substr($detectedDomain, 0, $lastColonPos);
            }
        }
    }

    $detectedDomain = rtrim($detectedDomain, '.');
}

// Installer lock is checked first to keep re-entry behavior deterministic.
if (is_file($lockPath)) {
    header('Location: /', true, 302);
    exit;
}

// Bring in Composer dependencies first; fallback autoloader keeps local classes available pre-install.
$composerAutoload = $root . '/composer/autoload.php';
if (is_file($composerAutoload)) {
    // Match runtime bootstrap behavior so EasyMDE's PHP bridge is not auto-loaded during install.
    $composerAutoloadFiles = $root . '/composer/composer/autoload_files.php';
    if (is_file($composerAutoloadFiles)) {
        /** @var mixed $autoloadFiles */
        $autoloadFiles = require $composerAutoloadFiles;
        if (is_array($autoloadFiles)) {
            if (!isset($GLOBALS['__composer_autoload_files']) || !is_array($GLOBALS['__composer_autoload_files'])) {
                $GLOBALS['__composer_autoload_files'] = [];
            }

            foreach ($autoloadFiles as $fileIdentifier => $filePath) {
                $normalizedPath = str_replace('\\', '/', (string) $filePath);
                if (str_contains($normalizedPath, '/tualo/easymde/src/functions.php')) {
                    $GLOBALS['__composer_autoload_files'][(string) $fileIdentifier] = true;
                }
            }
        }
    }

    require_once $composerAutoload;
}

spl_autoload_register(static function (string $class) use ($root): void {
    $prefix = 'Raven\\';
    if (!str_starts_with($class, $prefix)) {
        return;
    }

    $relative = str_replace('\\', '/', substr($class, strlen($prefix)));
    $path = $root . '/private/sys/' . $relative . '.php';
    if (is_file($path)) {
        require_once $path;
    }
});

// Session-backed CSRF token protects this high-impact setup endpoint.
if (session_status() !== PHP_SESSION_ACTIVE) {
    session_name('raven_install');
    session_set_cookie_params([
        'lifetime' => 0,
        'path' => '/',
        'domain' => '',
        'secure' => (!empty($_SERVER['HTTPS']) && strtolower((string) $_SERVER['HTTPS']) !== 'off'),
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    session_start();
}

if (!isset($_SESSION['_raven_install_csrf']) || !is_string($_SESSION['_raven_install_csrf'])) {
    $_SESSION['_raven_install_csrf'] = bin2hex(random_bytes(32));
}
$csrfToken = (string) $_SESSION['_raven_install_csrf'];

/** @var mixed $rawTemplate */
$rawTemplate = is_file($configTemplatePath) ? require $configTemplatePath : [];
$template = is_array($rawTemplate) ? $rawTemplate : [];

/** @var mixed $rawExisting */
$rawExisting = is_file($configPath) ? require $configPath : [];
$existing = is_array($rawExisting) ? $rawExisting : [];

$defaultConfig = $existing !== [] ? $existing : $template;
$defaultSiteDomain = trim((string) ($defaultConfig['site']['domain'] ?? ''));
if ($defaultSiteDomain === '') {
    $defaultSiteDomain = $detectedDomain;
}
$defaultTablePrefix = trim((string) ($defaultConfig['database']['table_prefix'] ?? ''));
if ($defaultTablePrefix === '') {
    $defaultTablePrefix = 'rvn_';
}
if ($existing === [] && strtolower($defaultTablePrefix) === 'raven_') {
    $defaultTablePrefix = 'rvn_';
}
$defaultDriver = strtolower(trim((string) ($defaultConfig['database']['driver'] ?? 'sqlite')));
if (!in_array($defaultDriver, ['sqlite', 'mysql', 'pgsql'], true)) {
    $defaultDriver = 'sqlite';
}
$defaultSiteName = trim((string) ($defaultConfig['site']['name'] ?? 'Raven CMS'));
if ($defaultSiteName === '') {
    $defaultSiteName = 'Raven CMS';
}
$defaultPanelPath = trim((string) ($defaultConfig['panel']['path'] ?? 'panel'));
if ($defaultPanelPath === '') {
    $defaultPanelPath = 'panel';
}

// Keep form values empty on first render so placeholders can guide typing without manual clearing.
$form = [
    'site_domain' => '',
    'site_name' => '',
    'panel_path' => '',
    'db_driver' => $defaultDriver,
    'db_table_prefix' => '',
    'mysql_host' => '',
    'mysql_port' => '',
    'mysql_dbname' => '',
    'mysql_user' => '',
    'mysql_password' => '',
    'mysql_charset' => '',
    'pgsql_host' => '',
    'pgsql_port' => '',
    'pgsql_dbname' => '',
    'pgsql_user' => '',
    'pgsql_password' => '',
    'enable_usernames' => '',
    'admin_username' => '',
    'admin_display_name' => '',
    'admin_email' => '',
    'admin_password' => '',
    'admin_password_confirm' => '',
];
$formPlaceholders = [
    'site_domain' => $defaultSiteDomain !== '' ? $defaultSiteDomain : 'example.com',
    'site_name' => $defaultSiteName,
    'panel_path' => $defaultPanelPath,
    'db_table_prefix' => $defaultTablePrefix,
    'mysql_host' => trim((string) ($defaultConfig['database']['mysql']['host'] ?? '127.0.0.1')),
    'mysql_port' => trim((string) ($defaultConfig['database']['mysql']['port'] ?? '3306')),
    'mysql_dbname' => trim((string) ($defaultConfig['database']['mysql']['dbname'] ?? 'raven')),
    'mysql_user' => trim((string) ($defaultConfig['database']['mysql']['user'] ?? 'raven')),
    'mysql_charset' => trim((string) ($defaultConfig['database']['mysql']['charset'] ?? 'utf8mb4')),
    'pgsql_host' => trim((string) ($defaultConfig['database']['pgsql']['host'] ?? '127.0.0.1')),
    'pgsql_port' => trim((string) ($defaultConfig['database']['pgsql']['port'] ?? '5432')),
    'pgsql_dbname' => trim((string) ($defaultConfig['database']['pgsql']['dbname'] ?? 'raven')),
    'pgsql_user' => trim((string) ($defaultConfig['database']['pgsql']['user'] ?? 'raven')),
    'admin_username' => 'optional',
    'admin_display_name' => 'Super Admin',
    'admin_email' => 'admin@example.com',
];

$errors = [];

if (strtoupper((string) ($_SERVER['REQUEST_METHOD'] ?? 'GET')) === 'POST') {
    foreach ($form as $key => $_) {
        $form[$key] = trim((string) ($_POST[$key] ?? ''));
    }

    if (!hash_equals($csrfToken, (string) ($_POST['_csrf'] ?? ''))) {
        $errors[] = 'Invalid form token. Reload the page and try again.';
    }

    $driver = strtolower($form['db_driver']);
    if (!in_array($driver, ['sqlite', 'mysql', 'pgsql'], true)) {
        $errors[] = 'Database driver must be sqlite, mysql, or pgsql.';
    }

    $siteDomain = $form['site_domain'] !== '' ? $form['site_domain'] : $formPlaceholders['site_domain'];
    $siteName = $form['site_name'] !== '' ? $form['site_name'] : $formPlaceholders['site_name'];
    $panelPathSource = $form['panel_path'] !== '' ? $form['panel_path'] : $formPlaceholders['panel_path'];
    $panelPath = strtolower($panelPathSource);

    if ($siteDomain === '') {
        $errors[] = 'Site domain is required.';
    }
    if ($siteName === '') {
        $errors[] = 'Site name is required.';
    }
    if ($panelPath === '' || preg_match('/^[a-z0-9][a-z0-9_-]*$/', $panelPath) !== 1) {
        $errors[] = 'Panel path must contain only lowercase letters, numbers, underscores, or dashes.';
    }

    $tablePrefixSource = $form['db_table_prefix'] !== '' ? $form['db_table_prefix'] : $formPlaceholders['db_table_prefix'];
    $tablePrefix = preg_replace('/[^a-zA-Z0-9_]/', '', $tablePrefixSource) ?? '';
    if ($driver === 'sqlite') {
        $sqliteBasePath = $sqliteDefaultBasePath;
    } else {
        $sqliteBasePath = $sqliteDefaultBasePath;
    }

    $mysqlHost = $form['mysql_host'] !== '' ? $form['mysql_host'] : $formPlaceholders['mysql_host'];
    $mysqlPortRaw = $form['mysql_port'] !== '' ? $form['mysql_port'] : $formPlaceholders['mysql_port'];
    $mysqlPort = (int) $mysqlPortRaw;
    $mysqlDbName = $form['mysql_dbname'] !== '' ? $form['mysql_dbname'] : $formPlaceholders['mysql_dbname'];
    $mysqlUser = $form['mysql_user'] !== '' ? $form['mysql_user'] : $formPlaceholders['mysql_user'];
    $mysqlCharset = $form['mysql_charset'] !== '' ? $form['mysql_charset'] : $formPlaceholders['mysql_charset'];
    if ($driver === 'mysql') {
        if ($mysqlHost === '' || $mysqlDbName === '' || $mysqlUser === '') {
            $errors[] = 'MySQL host, database, and user are required.';
        }
        if ($mysqlPort < 1 || $mysqlPort > 65535) {
            $errors[] = 'MySQL port must be between 1 and 65535.';
        }
        if ($mysqlCharset === '') {
            $errors[] = 'MySQL charset is required.';
        }
    }

    $pgsqlHost = $form['pgsql_host'] !== '' ? $form['pgsql_host'] : $formPlaceholders['pgsql_host'];
    $pgsqlPortRaw = $form['pgsql_port'] !== '' ? $form['pgsql_port'] : $formPlaceholders['pgsql_port'];
    $pgsqlPort = (int) $pgsqlPortRaw;
    $pgsqlDbName = $form['pgsql_dbname'] !== '' ? $form['pgsql_dbname'] : $formPlaceholders['pgsql_dbname'];
    $pgsqlUser = $form['pgsql_user'] !== '' ? $form['pgsql_user'] : $formPlaceholders['pgsql_user'];
    if ($driver === 'pgsql') {
        if ($pgsqlHost === '' || $pgsqlDbName === '' || $pgsqlUser === '') {
            $errors[] = 'PostgreSQL host, database, and user are required.';
        }
        if ($pgsqlPort < 1 || $pgsqlPort > 65535) {
            $errors[] = 'PostgreSQL port must be between 1 and 65535.';
        }
    }

    $enableUsernames = (string) ($form['enable_usernames'] ?? '') === '1';
    $adminUsername = $enableUsernames ? $form['admin_username'] : '';
    $adminDisplayName = $form['admin_display_name'] !== ''
        ? $form['admin_display_name']
        : $formPlaceholders['admin_display_name'];
    $adminEmail = $form['admin_email'] !== '' ? $form['admin_email'] : $formPlaceholders['admin_email'];
    $adminPassword = $form['admin_password'];
    $adminPasswordConfirm = $form['admin_password_confirm'];

    if ($enableUsernames && preg_match('/^[a-zA-Z0-9_.-]{3,100}$/', $adminUsername) !== 1) {
        $errors[] = 'Admin username is required and must be 3-100 characters using letters, numbers, dot, underscore, or dash.';
    }
    if ($adminEmail === '' || filter_var($adminEmail, FILTER_VALIDATE_EMAIL) === false) {
        $errors[] = 'A valid admin email is required.';
    }
    if ($adminDisplayName === '') {
        $adminDisplayName = $adminEmail;
    }
    if (strlen($adminPassword) < 8) {
        $errors[] = 'Admin password must be at least 8 characters.';
    }
    if (!hash_equals($adminPassword, $adminPasswordConfirm)) {
        $errors[] = 'Admin password confirmation does not match.';
    }

    if ($errors === []) {
        $nextConfig = is_array($template) && $template !== [] ? $template : [];

        // Keep installer output aligned with panel config editor expectations.
        $nextConfig['site'] = [
            'domain' => $siteDomain,
            'name' => $siteName,
            'enabled' => 'public',
            'default_theme' => trim((string) ($nextConfig['site']['default_theme'] ?? 'raven')) !== ''
                ? trim((string) ($nextConfig['site']['default_theme'] ?? 'raven'))
                : 'raven',
        ];

        $nextConfig['panel'] = is_array($nextConfig['panel'] ?? null) ? $nextConfig['panel'] : [];
        $nextConfig['panel']['path'] = $panelPath;
        if (!array_key_exists('default_theme', $nextConfig['panel'])) {
            $nextConfig['panel']['default_theme'] = 'light';
        }
        if (!array_key_exists('brand_name', $nextConfig['panel'])) {
            $nextConfig['panel']['brand_name'] = $siteName;
        }
        if (!array_key_exists('brand_logo', $nextConfig['panel'])) {
            $nextConfig['panel']['brand_logo'] = '';
        }
        unset($nextConfig['public']);
        $nextConfig['user'] = is_array($nextConfig['user'] ?? null) ? $nextConfig['user'] : [];
        $nextConfig['user']['auth'] = is_array($nextConfig['user']['auth'] ?? null) ? $nextConfig['user']['auth'] : [];
        $nextConfig['user']['auth']['login'] = $enableUsernames ? 'username' : 'email';
        $nextConfig['user']['auth']['registration'] = 'closed';

        $nextConfig['database'] = [
            'driver' => $driver,
            'sqlite' => [
                'base_path' => $sqliteBasePath,
            ],
            'mysql' => [
                'host' => $mysqlHost,
                'port' => $mysqlPort > 0 ? $mysqlPort : 3306,
                'dbname' => $mysqlDbName,
                'user' => $mysqlUser,
                'password' => $form['mysql_password'],
                'charset' => $mysqlCharset !== '' ? $mysqlCharset : 'utf8mb4',
            ],
            'pgsql' => [
                'host' => $pgsqlHost,
                'port' => $pgsqlPort > 0 ? $pgsqlPort : 5432,
                'dbname' => $pgsqlDbName,
                'user' => $pgsqlUser,
                'password' => $form['pgsql_password'],
            ],
            'table_prefix' => $tablePrefix,
        ];

        // Installer replaces bootstrap seeding; remove any legacy key entirely.
        unset($nextConfig['bootstrap_admin']);

        try {
            // Create SQLite storage directory only when SQLite is selected during install.
            if ($driver === 'sqlite') {
                if (!is_dir($sqliteBasePath) && !mkdir($sqliteBasePath, 0775, true) && !is_dir($sqliteBasePath)) {
                    throw new RuntimeException('Failed to create SQLite base path directory.');
                }
            }

            $connectionFactory = new ConnectionFactory((array) ($nextConfig['database'] ?? []));
            $driverName = $connectionFactory->getDriver();
            $prefix = $connectionFactory->getPrefix();

            $appDb = $connectionFactory->createAppConnection();
            $authDb = $connectionFactory->createAuthConnection();

            $schema = new SchemaManager();
            $schema->ensure($appDb, $authDb, $driverName, $prefix);

            $users = new UserRepository($authDb, $appDb, $driverName, $prefix);
            if ($users->listAll() !== []) {
                throw new RuntimeException('Installer can only create the initial admin on an empty user database.');
            }

            $groups = new GroupRepository($appDb, $driverName, $prefix);
            $superAdminGroupId = $groups->idBySlug('super');
            if ($superAdminGroupId === null) {
                throw new RuntimeException('Stock groups were not created correctly.');
            }

            $users->save([
                'id' => null,
                'username' => $adminUsername,
                'display_name' => $adminDisplayName,
                'email' => $adminEmail,
                'theme' => 'default',
                'password' => $adminPassword,
                'group_ids' => [$superAdminGroupId],
            ]);

            installer_write_config($configPath, $nextConfig);

            // Seed runtime extension state from committed defaults template.
            if (!is_file($extensionStateTemplatePath)) {
                throw new RuntimeException('Missing extension state template private/dat/ext/.state.php.dist.');
            }

            $stateTemplateContent = file_get_contents($extensionStateTemplatePath);
            if ($stateTemplateContent === false || trim($stateTemplateContent) === '') {
                throw new RuntimeException('Extension state template is unreadable or empty.');
            }

            $stateDirectory = dirname($extensionStatePath);
            if (!is_dir($stateDirectory) && !mkdir($stateDirectory, 0775, true) && !is_dir($stateDirectory)) {
                throw new RuntimeException('Failed to create extension state directory.');
            }

            if (file_put_contents($extensionStatePath, $stateTemplateContent, LOCK_EX) === false) {
                throw new RuntimeException('Failed to write private/dat/ext/.state.php.');
            }

            $lockDirectory = dirname($lockPath);
            if (!is_dir($lockDirectory) && !mkdir($lockDirectory, 0775, true) && !is_dir($lockDirectory)) {
                throw new RuntimeException('Failed to create installer lock directory.');
            }

            $lockContent = "Raven CMS installer lock\nInstalled at (UTC): " . gmdate('c') . "\n";
            if (file_put_contents($lockPath, $lockContent, LOCK_EX) === false) {
                throw new RuntimeException('Failed to write installer lock file.');
            }

            header('Location: /', true, 302);
            exit;
        } catch (\Throwable $exception) {
            $errors[] = 'Installation failed: ' . $exception->getMessage();
        }
    }
}
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Raven CMS Installer</title>
    <style>
        body { font-family: sans-serif; background: #f4f6f8; color: #1a1f24; margin: 0; }
        .wrap { max-width: 920px; margin: 2rem auto; padding: 0 1rem 2rem; }
        .card { background: #fff; border: 1px solid #d7dde5; border-radius: 8px; padding: 1.25rem; margin-bottom: 1rem; }
        h1, h2 { margin: 0 0 0.8rem; }
        h1 { font-size: 1.45rem; }
        h2 { font-size: 1.05rem; border-bottom: 1px solid #edf1f5; padding-bottom: 0.45rem; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0.85rem 1rem; }
        .field { display: flex; flex-direction: column; gap: 0.3rem; }
        .field.full { grid-column: 1 / -1; }
        label { font-size: 0.9rem; font-weight: 600; }
        input, select { border: 1px solid #b8c3d1; border-radius: 6px; padding: 0.5rem 0.55rem; font-size: 0.95rem; }
        input::placeholder { color: #7d8998; opacity: 1; }
        .note { font-size: 0.86rem; color: #4d5b6b; margin-top: 0.25rem; }
        .alert { border-radius: 6px; padding: 0.8rem 0.9rem; margin-bottom: 1rem; }
        .alert.error { background: #fcebec; border: 1px solid #f3b4b8; color: #7a1f26; }
        .actions { display: flex; justify-content: flex-end; margin-top: 1rem; }
        button { background: #154f95; color: #fff; border: 0; border-radius: 6px; padding: 0.62rem 1rem; font-size: 0.95rem; cursor: pointer; }
        button:hover { background: #123f77; }
        [data-driver-section] { display: none; }
        @media (max-width: 800px) { .grid { grid-template-columns: 1fr; } }
    </style>
</head>
<body>
<div class="wrap">
    <div class="card">
        <h1>Raven CMS Installer</h1>
    </div>

    <?php if ($errors !== []): ?>
        <div class="alert error">
            <strong>Install could not complete.</strong>
            <ul>
                <?php foreach ($errors as $error): ?>
                    <li><?= installer_e($error) ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <form method="post" action="/install.php" novalidate>
        <input type="hidden" name="_csrf" value="<?= installer_e($csrfToken) ?>">

        <div class="card">
            <h2>Site</h2>
            <div class="grid">
                <div class="field">
                    <label for="site_domain">Domain</label>
                    <input id="site_domain" name="site_domain" value="<?= installer_e($form['site_domain']) ?>" placeholder="<?= installer_e($formPlaceholders['site_domain']) ?>" required>
                    <div class="note">Example: <code>example.com</code></div>
                </div>
                <div class="field">
                    <label for="site_name">Site Name</label>
                    <input id="site_name" name="site_name" value="<?= installer_e($form['site_name']) ?>" placeholder="<?= installer_e($formPlaceholders['site_name']) ?>" required>
                </div>
                <div class="field">
                    <label for="panel_path">Panel Path</label>
                    <input id="panel_path" name="panel_path" value="<?= installer_e($form['panel_path']) ?>" placeholder="<?= installer_e($formPlaceholders['panel_path']) ?>" required>
                    <div class="note">Example: <code>panel</code> for <code>/panel</code></div>
                </div>
            </div>
        </div>

        <div class="card">
            <h2>Database</h2>
            <div class="grid">
                <div class="field">
                    <label for="db_driver">Driver</label>
                    <select id="db_driver" name="db_driver" required>
                        <option value="sqlite"<?= $form['db_driver'] === 'sqlite' ? ' selected' : '' ?>>SQLite</option>
                        <option value="mysql"<?= $form['db_driver'] === 'mysql' ? ' selected' : '' ?>>MySQL / MariaDB</option>
                        <option value="pgsql"<?= $form['db_driver'] === 'pgsql' ? ' selected' : '' ?>>PostgreSQL</option>
                    </select>
                </div>
                <div class="field" id="db_table_prefix_field">
                    <label for="db_table_prefix">Table Prefix (MySQL/PostgreSQL)</label>
                    <input id="db_table_prefix" name="db_table_prefix" value="<?= installer_e($form['db_table_prefix']) ?>" placeholder="<?= installer_e($formPlaceholders['db_table_prefix']) ?>">
                </div>
            </div>

            <div class="grid" data-driver-section="sqlite">
                <div class="field full">
                    <label>SQLite Storage</label>
                    <div class="note">SQLite files are stored automatically in <code>private/dat/db/</code>.</div>
                </div>
            </div>

            <div class="grid" data-driver-section="mysql">
                <div class="field"><label for="mysql_host">MySQL Host</label><input id="mysql_host" name="mysql_host" value="<?= installer_e($form['mysql_host']) ?>" placeholder="<?= installer_e($formPlaceholders['mysql_host']) ?>"></div>
                <div class="field"><label for="mysql_port">MySQL Port</label><input id="mysql_port" name="mysql_port" value="<?= installer_e($form['mysql_port']) ?>" placeholder="<?= installer_e($formPlaceholders['mysql_port']) ?>"></div>
                <div class="field"><label for="mysql_dbname">MySQL Database</label><input id="mysql_dbname" name="mysql_dbname" value="<?= installer_e($form['mysql_dbname']) ?>" placeholder="<?= installer_e($formPlaceholders['mysql_dbname']) ?>"></div>
                <div class="field"><label for="mysql_user">MySQL User</label><input id="mysql_user" name="mysql_user" value="<?= installer_e($form['mysql_user']) ?>" placeholder="<?= installer_e($formPlaceholders['mysql_user']) ?>"></div>
                <div class="field"><label for="mysql_password">MySQL Password</label><input id="mysql_password" name="mysql_password" type="password" value="<?= installer_e($form['mysql_password']) ?>"></div>
                <div class="field"><label for="mysql_charset">MySQL Charset</label><input id="mysql_charset" name="mysql_charset" value="<?= installer_e($form['mysql_charset']) ?>" placeholder="<?= installer_e($formPlaceholders['mysql_charset']) ?>"></div>
            </div>

            <div class="grid" data-driver-section="pgsql">
                <div class="field"><label for="pgsql_host">PostgreSQL Host</label><input id="pgsql_host" name="pgsql_host" value="<?= installer_e($form['pgsql_host']) ?>" placeholder="<?= installer_e($formPlaceholders['pgsql_host']) ?>"></div>
                <div class="field"><label for="pgsql_port">PostgreSQL Port</label><input id="pgsql_port" name="pgsql_port" value="<?= installer_e($form['pgsql_port']) ?>" placeholder="<?= installer_e($formPlaceholders['pgsql_port']) ?>"></div>
                <div class="field"><label for="pgsql_dbname">PostgreSQL Database</label><input id="pgsql_dbname" name="pgsql_dbname" value="<?= installer_e($form['pgsql_dbname']) ?>" placeholder="<?= installer_e($formPlaceholders['pgsql_dbname']) ?>"></div>
                <div class="field"><label for="pgsql_user">PostgreSQL User</label><input id="pgsql_user" name="pgsql_user" value="<?= installer_e($form['pgsql_user']) ?>" placeholder="<?= installer_e($formPlaceholders['pgsql_user']) ?>"></div>
                <div class="field"><label for="pgsql_password">PostgreSQL Password</label><input id="pgsql_password" name="pgsql_password" type="password" value="<?= installer_e($form['pgsql_password']) ?>"></div>
            </div>
        </div>

        <div class="card">
            <h2>First Super Admin</h2>
            <div class="grid">
                <div class="field full">
                    <label for="enable_usernames" style="display:flex;align-items:center;gap:0.45rem;">
                        <input id="enable_usernames" name="enable_usernames" type="checkbox" value="1"<?= (string) ($form['enable_usernames'] ?? '') === '1' ? ' checked' : '' ?>>
                        <span>Enable usernames for panel login</span>
                    </label>
                    <div class="note">When enabled, login mode is set to username and an admin username is required.</div>
                </div>
                <div class="field" id="admin_username_field"<?= (string) ($form['enable_usernames'] ?? '') === '1' ? '' : ' style="display:none;"' ?>>
                    <label for="admin_username">Username</label>
                    <input
                        id="admin_username"
                        name="admin_username"
                        value="<?= installer_e($form['admin_username']) ?>"
                        placeholder="<?= installer_e($formPlaceholders['admin_username']) ?>"
                        <?= (string) ($form['enable_usernames'] ?? '') === '1' ? 'required' : 'disabled' ?>
                    >
                    <div class="note">Used as the panel login identifier when usernames are enabled.</div>
                </div>
                <div class="field"><label for="admin_display_name">Display Name</label><input id="admin_display_name" name="admin_display_name" value="<?= installer_e($form['admin_display_name']) ?>" placeholder="<?= installer_e($formPlaceholders['admin_display_name']) ?>"></div>
                <div class="field"><label for="admin_email">Email</label><input id="admin_email" name="admin_email" type="email" value="<?= installer_e($form['admin_email']) ?>" placeholder="<?= installer_e($formPlaceholders['admin_email']) ?>" required></div>
                <div class="field"><label for="admin_password">Password</label><input id="admin_password" name="admin_password" type="password" required></div>
                <div class="field"><label for="admin_password_confirm">Confirm Password</label><input id="admin_password_confirm" name="admin_password_confirm" type="password" required></div>
            </div>
        </div>

        <div class="actions">
            <button type="submit">Run Installer</button>
        </div>
    </form>
</div>
<script>
  (function () {
    var driverSelect = document.getElementById('db_driver');
    if (!(driverSelect instanceof HTMLSelectElement)) {
      return;
    }
    var tablePrefixField = document.getElementById('db_table_prefix_field');
    var tablePrefixInput = document.getElementById('db_table_prefix');
    var enableUsernamesInput = document.getElementById('enable_usernames');
    var adminUsernameField = document.getElementById('admin_username_field');
    var adminUsernameInput = document.getElementById('admin_username');

    function syncDriverSections() {
      var selected = driverSelect.value;
      var sections = document.querySelectorAll('[data-driver-section]');
      sections.forEach(function (section) {
        if (!(section instanceof HTMLElement)) {
          return;
        }

        section.style.display = section.getAttribute('data-driver-section') === selected ? 'grid' : 'none';
      });

      if (tablePrefixField instanceof HTMLElement) {
        tablePrefixField.style.display = selected === 'sqlite' ? 'none' : '';
      }
      if (tablePrefixInput instanceof HTMLInputElement) {
        tablePrefixInput.disabled = selected === 'sqlite';
      }
    }

    driverSelect.addEventListener('change', syncDriverSections);
    syncDriverSections();

    function syncUsernameFields() {
      var enabled = enableUsernamesInput instanceof HTMLInputElement && enableUsernamesInput.checked;
      if (adminUsernameField instanceof HTMLElement) {
        adminUsernameField.style.display = enabled ? '' : 'none';
      }
      if (adminUsernameInput instanceof HTMLInputElement) {
        adminUsernameInput.disabled = !enabled;
        adminUsernameInput.required = enabled;
      }
    }

    if (enableUsernamesInput instanceof HTMLInputElement) {
      enableUsernamesInput.addEventListener('change', syncUsernameFields);
    }
    syncUsernameFields();
  })();
</script>
</body>
</html>
