<?php

/**
 * RAVEN CMS
 * ~/private/src/Core/Config.php
 * Core framework component used by Raven CMS.
 * Docs: https://raven.lanterns.io
 */

// Inline note: Core utilities are shared by both public and panel runtime flows.

declare(strict_types=1);

namespace Raven\Core;

use RuntimeException;

/**
 * Loads and saves Raven configuration from a PHP array file.
 *
 * The panel uses this class to safely edit config values while keeping the
 * canonical config format in `private/config.php`.
 */
final class Config
{
    /** @var array<string, mixed> Parsed config tree. */
    private array $data;

    /** Absolute path to the config file on disk. */
    private string $path;

    /**
     * @param string $path Absolute path to `private/config.php`.
     */
    public function __construct(string $path)
    {
        $this->path = $path;

        /** @var mixed $loaded */
        $loaded = require $path;

        if (!is_array($loaded)) {
            throw new RuntimeException('Config file must return an array.');
        }

        $this->data = $loaded;
    }

    /**
     * Returns full config tree for read-only use.
     *
     * @return array<string, mixed>
     */
    public function all(): array
    {
        return $this->data;
    }

    /**
     * Reads a config value using dot notation, e.g. `panel.path`.
     *
     * @param mixed $default
     *
     * @return mixed
     */
    public function get(string $key, mixed $default = null): mixed
    {
        $segments = explode('.', $key);
        $cursor = $this->data;

        foreach ($segments as $segment) {
            if (!is_array($cursor) || !array_key_exists($segment, $cursor)) {
                return $default;
            }

            $cursor = $cursor[$segment];
        }

        return $cursor;
    }

    /**
     * Writes a config value into the in-memory tree via dot notation.
     */
    public function set(string $key, mixed $value): void
    {
        $segments = explode('.', $key);
        $cursor = &$this->data;

        foreach ($segments as $index => $segment) {
            // Create intermediate arrays when a new path segment is introduced.
            if (!is_array($cursor)) {
                $cursor = [];
            }

            if ($index === count($segments) - 1) {
                $cursor[$segment] = $value;
                return;
            }

            if (!isset($cursor[$segment]) || !is_array($cursor[$segment])) {
                $cursor[$segment] = [];
            }

            $cursor = &$cursor[$segment];
        }
    }

    /**
     * Replaces full config tree in memory.
     *
     * @param array<string, mixed> $data
     */
    public function replace(array $data): void
    {
        $this->data = $data;
    }

    /**
     * Persists the current config tree back to disk in executable PHP format.
     */
    public function save(): void
    {
        $export = var_export($this->data, true);

        $content = "<?php\n\n";
        $content .= "/**\n";
        $content .= " * RAVEN CMS\n";
        $content .= " * ~/private/config.php\n";
        $content .= " * Runtime configuration values for Raven CMS.\n";
        $content .= " * Docs: https://raven.lanterns.io\n";
        $content .= " */\n\n";
        $content .= "// Inline note: Keep site/database defaults explicit so panel config editing stays predictable.\n\n";
        $content .= "declare(strict_types=1);\n\n";
        $content .= "/**\n";
        $content .= " * Raven runtime configuration (generated by panel editor).\n";
        $content .= " */\n";
        $content .= "return " . $export . ";\n";

        $written = file_put_contents($this->path, $content, LOCK_EX);

        if ($written === false) {
            throw new RuntimeException('Failed to save config file.');
        }

        // Ensure immediately following requests read the updated config file
        // even when opcache uses a non-zero revalidation interval.
        clearstatcache(true, $this->path);
        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($this->path, true);
        }
    }
}
