<?php

/**
 * RAVEN CMS
 * ~/private/sys/Repository/ConfigWrite.php
 * Repository-style config writer for nested updates and on-disk persistence.
 * Docs: https://lanterns.io/raven
 */

declare(strict_types=1);

namespace Raven\Core\Repository;

use RuntimeException;

/**
 * Writes a PHP config array to disk in the canonical Raven config-file format.
 */
final class ConfigWrite
{
    /**
     * Writes one dot-delimited config value into an array tree.
     *
     * @param array<string, mixed> $config Config tree being mutated.
     * @param string $key Dot-delimited config key path.
     * @param mixed $value Value to store at the resolved path.
     * @return void
     */
    public static function set(array &$config, string $key, mixed $value): void
    {
        self::setNested($config, ConfigRead::segments($key), $value);
    }

    /**
     * Writes one nested config value into an array tree by path segments.
     *
     * @param array<string, mixed> $config Config tree being mutated.
     * @param array<int, string> $segments Nested config path segments.
     * @param mixed $value Value to store at the resolved path.
     * @return void
     */
    public static function setNested(array &$config, array $segments, mixed $value): void
    {
        // Empty segment lists cannot identify a write destination.
        if ($segments === []) {
            return;
        }

        $cursor = &$config;
        $lastIndex = count($segments) - 1;

        // Walk each segment, creating intermediate arrays as needed.
        foreach ($segments as $index => $segment) {
            // Final segment receives the assigned value and ends traversal.
            if ($index === $lastIndex) {
                $cursor[$segment] = $value;
                return;
            }

            // Materialize missing/non-array branches so nested assignment can continue safely.
            if (!isset($cursor[$segment]) || !is_array($cursor[$segment])) {
                $cursor[$segment] = [];
            }

            $cursor = &$cursor[$segment];
        }
    }

    /**
     * Persists one config value while leaving the rest of the file untouched.
     *
     * @param string $path Absolute path to the config file on disk.
     * @param array<string, mixed> $data Current config tree.
     * @param string $key Dot-delimited config key path.
     * @param mixed $value Value to persist at the resolved path.
     * @throws RuntimeException When the file cannot be written.
     * @return array<string, mixed> Updated config tree after the write.
     */
    public static function persistValue(string $path, array $data, string $key, mixed $value): array
    {
        self::set($data, $key, $value);
        self::persist($path, $data);

        return $data;
    }

    /**
     * Persists a config array to a PHP file at the given path.
     *
     * @param string $path Absolute path to the config file on disk.
     * @param array<string, mixed> $data Config tree to persist.
     * @throws RuntimeException When the file cannot be written.
     * @return void
     */
    public static function persist(string $path, array $data): void
    {
        $export = var_export($data, true);
        $content = <<<PHP
<?php

/**
 * RAVEN CMS
 * ~/private/dat/config.php
 * Runtime configuration values for Raven CMS.
 * Docs: https://lanterns.io/raven
 */

// Inline note: Keep site/database defaults explicit so panel config editing stays predictable.

declare(strict_types=1);

/**
 * Raven runtime configuration (generated by panel editor).
 */
return {$export};

PHP;

        $written = file_put_contents($path, $content, LOCK_EX);
        // Fail fast when config file cannot be written to disk.
        if ($written === false) {
            throw new RuntimeException('Failed to save config file.');
        }

        clearstatcache(true, $path);
        // Refresh OPcache entry when extension is available so runtime sees updated config.
        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($path, true);
        }
    }
}
